across-protocol/contracts

.github/workflows/test.yml, package.json
=> feat(github-actions): Add hardhat test to CI

contracts/HubPool.sol, test/HubPool.Admin.ts, test/HubPool.DisputeRootBundle.ts, test/HubPool.Fixture.ts, test/HubPool.LiquidityProvisionFees.ts, test/HubPool.ProposeRootBundle.ts, test/constants.ts
Mostly just tracked the TODOs in #45 with some minor naming changes. Will write tests once we agree that these changes are what we want.
=> feat: todos on HubPool setters

contracts/chain-adapters/Mock_Adapter.sol, test/HubPool.ExecuteRootBundle.ts, test/gas-analytics/HubPool.RefundExecution.ts
This PR intends to make the gas estimates more realistic.
=> feat: update gas estimation script

.npmignore, package.json
=> changes for npm release

package.json, test/fixtures/SpokePool.Fixture.ts
small nit to fix one of the helpers used in relayer tests.
=> feat: Further helper update

contracts/HubPool.sol, contracts/SpokePoolInterface.sol
Addresses a lossed comment change due to merge issues.
=> fix:N06 address issue arising from merge conflict

contracts/HubPool.sol
There was a small type as a result of a merge conflict during audit fixes. This PR addresses to correctly fix issue N09.
=> fix:N09: address issue arising from merge conflict

tasks/enableL1TokenAcrossEcosystem.ts
=> improve: Update setupL1 task with warning about ConfigStore setup

.github/workflows/publish.yml
Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>
=> Fix: Package publish

package.json
Main new features: new license, bump dependencies, fix usdt in spoke pool and import merkletree
=> feat: new release

contracts/Ovm_SpokePool.sol, contracts/chain-adapters/Optimism_Adapter.sol
SNX doesn't conform to Optimism bridge standard, handle SNX explicitly:
- L1ToL2Bridge: https://github.com/Synthetixio/synthetix/blob/develop/contracts/SynthetixBridgeToOptimism.sol#L89
- L2ToL1Bridge: https://github.com/Synthetixio/synthetix/blob/develop/contracts/SynthetixBridgeToBase.sol#L50
=> feat: Support SNX bridging to Optimism via non-standard bridge

contracts/SpokePool.sol
Will make certain dataworker functions more efficient. See `queryHistoricalMatchingFills` in https://github.com/across-protocol/relayer-v2/pull/382/files
=> feat: Index depositId in FilledRelay events

contracts/SpokePool.sol
Trying to keep the interface changes to a minimum
=> improve: Revert renaming of RequestedSpeedUpDeposit param

.github/workflows/publish.yml, package.json
Changes publish.yml file to support pre-releases. Inspired by [this package](https://github.com/marketplace/actions/github-releases-for-automated-package-publishing)
=> feat: Support pre-releases

utils/constants.ts
=> feat: add SNX to token constant

package.json
Bump version for a new release with SNX in constants file.
=> chore: bump v2.2.2

utils/constants.ts
Based on addresses listed here https://dev.pooltogether.com/protocol/deployments/governance
=> feat: add POOL to constants

contracts/SpokePoolVerifier.sol
I accidentally merged the previous PR with an old license.
=> fix: fix incorrect license

package.json
I had intended to only bump the patch level, but was surprised when I saw how much has been committed since the last release.
=> chore: Bump minor

package.json
After upgrade of UMA dependencies.
=> chore: Bump patch level

contracts/chain-adapters/CrossDomainEnabled.sol
=> docs: update comment

contracts/SpokePool.sol, contracts/interfaces/USSSpokePoolInterface.sol
=> feat(SpokePool): Add USS SpeedUp creation and verification methods

contracts/test/MockSpokePool.sol, test/SpokePool.ExecuteRootBundle.ts
=> feat: Add _distributeRelayerRefund() unit tests

contracts/SpokePool.sol
#379 added this new public mapping and we forgot to decrement the storage gap
Additionallly #379 did not move the new mapping to the bottom of the storage slots
=> fix(SpokePool): Decrement __gap due to new fillStatuses mapping and fix storage slot layout

test/SpokePool.Relay.ts
We are missing a unit test that ensures that the _verifyUSSDepositorSignature correctly implements EIP1271 signing
=> feat(SpokePool): Add EIP1271 signature test for USS speedup function

contracts/SpokePool.sol, contracts/interfaces/USSSpokePoolInterface.sol
=> feat(SpokePool): Add Natspec comments

contracts/SwapAndBridge.sol
implement a contract to atomically swap tokens before submitting for Across deposit.
Fixes ACX-1785
=> feat: Add SwapAndBridge helper contract

contracts/MerkleLib.sol, contracts/Polygon_SpokePool.sol, contracts/SpokePool.sol, contracts/interfaces/SpokePoolInterface.sol
Signed-off-by: Matt Rice <matthewcrice32@gmail.com>
Co-authored-by: nicholaspai <npai.nyc@gmail.com>
=> improve: Mark functions that are soon to be deprecated post USS deployment (#3)

package.json, test/fixtures/SpokePool.Fixture.ts
This eases the test implementation downstream in sdk-v2.
=> improve(test): Allow caller to identify SpokePool contract

deployments/deployments.json, package.json, yarn.lock
This PR reflects a series of testnet deployments made with a MockSpokePool on Ethereum Sepolia & Sepolia-based L2 chains.
=> feat(testnet): add deployment addresses for sepolia

contracts/SwapAndBridge.sol
The SwapAndBridge contract enables swapping an amount of tokens via a decentralized exchange service of preference and then bridge the swapped amount via Across. Both swap and bridging actions take place within a single transaction. To execute the swap, the SwapAndBridge contract performs a low level call to the designated exchange contract. For this call, the calldata parameters are arbitrarily given by the user. The only restriction is that the called function selector must be different than an ERC-20 token's transferFrom function.
Performing a low level call with arbitrary data to an external contract should be avoided as it increases the possible attack surface.
Instead of blacklisting the suspicious calldata parameters, consider whitelisting the allowed ones. More specifically, …
=> improve: L05 Low Level Call to External Exchange Contract With Arbitrary Calldata

deploy/032_deploy_uniswap_swap_and_bridge.ts, deploy/034_deploy_1inch_swap_and_bridge.ts, package.json, tasks/enableL1TokenAcrossEcosystem.ts, yarn.lock
This constants version deprecates _USDC in favor of USDC
=> chore: Update constants-v2 to 1.1.0

contracts/upgradeable/MultiCallerUpgradeable.sol
=> improve(MultiCallerUpgradeable): Replace post increment

contracts/Ovm_SpokePool.sol
=> improve(OVM_SpokePool): Update comments about bridgeERC20To/withdrawTo

contracts/test/MockBlastUsdYieldManager.sol, test/foundry/local/Blast_DaiRetriever.sol
Simple tests to prevent future regressions
=> improve: Add unit tests for Blast_DaiRetriever

contracts/SpokePool.sol, contracts/interfaces/V3SpokePoolInterface.sol, test/evm/hardhat/SpokePool.Deposit.ts, test/evm/hardhat/fixtures/SpokePool.Fixture.ts
This reverts commit 9d21d1ba12ef10751e1b33e09556b6c0b10883cc.
This should be removed from master and audited as a separate diff.
=> Revert "feat(SpokePool): Introduce opt-in deterministic relay data hashes (#583)"

README.md
=> fix: Update readme with anchor build instructions

programs/svm-spoke/src/instructions/admin.rs, programs/svm-spoke/src/instructions/deposit.rs, programs/svm-spoke/src/instructions/fill.rs
- Add Todos from first coding reading session
=> feat: add todos from first code reading session

scripts/svm/closeDataWorkerLookUpTables.ts, scripts/svm/closeRelayerPdas.ts, scripts/svm/enableRoute.ts, scripts/svm/initialize.ts, scripts/svm/queryDeposits.ts, scripts/svm/queryFills.ts, scripts/svm/queryRoute.ts, scripts/svm/queryState.ts, scripts/svm/remotePauseDeposits.ts, scripts/svm/simpleDeposit.ts, scripts/svm/simpleFakeRelayerRepayment.ts, scripts/svm/simpleFill.ts, src/SvmUtils.ts, test/svm/SvmSpoke.Bundle.ts, test/svm/SvmSpoke.HandleReceiveMessage.ts, test/svm/SvmSpoke.SlowFill.ts, test/svm/SvmSpoke.TokenBridge.ts, test/svm/Utils.Events.ts
=> nit: Improve SVM tests and scripts

hardhat.config.ts, package.json, tasks/testChainAdapter.ts, yarn.lock
This has some limitations around USDC native/bridged coincidence, but should otherwise be useful for testing chain adapters for new deployments (where CCTP is very unlikely to be enabled anyway).
=> feat: hardhat task to test chain adapter token bridging (#669)

test/svm/SvmSpoke.HandleReceiveMessage.ts
- Add test to check that ccpt messages can't be replayed
=> test(svm): add cctp messages replay test

programs/svm-spoke/src/instructions/handle_receive_message.rs, programs/svm-spoke/src/lib.rs
=> feat: WIPs from code reading session 3

test/evm/hardhat/SpokePool.Deposit.ts
small PR to remove logs where they should not be.
=> Fix: remove two small console logs from tests

package.json
=> chore(aleph-zero): bump to new contracts version

.github/workflows/publish.yml, package.json
Bumping version again as last release failed
=> chore: bump contracts version

contracts/SpokePool.sol, contracts/interfaces/V3SpokePoolInterface.sol, test/evm/hardhat/SpokePool.Deposit.ts, test/evm/hardhat/constants.ts
- Fix stack to deep error in _depositV3 by combining the function arguments into a struct `DepositV3Params`
- Fix tests
=> fix: stack too deep

contracts/SpokePool.sol, contracts/test/MockSpokePool.sol
This reverts commit 85f00011d5360163172295b7f9d08381c1f253b7.
=> Revert "feat: update depositor to bytes32"

programs/svm-spoke/src/event.rs, programs/svm-spoke/src/instructions/admin.rs
PR to apply https://github.com/across-protocol/contracts/pull/760 only to rust code to merge into master.
=> fix: apply EmergencyDeletedRootBundle event change to rust only

programs/svm-spoke/src/event.rs, programs/svm-spoke/src/instructions/bundle.rs, test/svm/SvmSpoke.Bundle.ts
=> feat: add missing TokensBridged event when amount_to_return > 0

test/svm/SvmSpoke.Bundle.ts
=> fix(svm): linter issues

test/svm/SvmSpoke.common.ts
- Fix random seed collision
There was a collision in this test run:
https://github.com/across-protocol/contracts/actions/runs/12146310287/job/33869919814
=> fix(svm): random seed collision tests

Anchor.toml, scripts/svm/remoteHubPoolPauseDeposits.ts
=> feat: add pause deposits script

scripts/svm/bridgeLiabilityToHubPool.ts, scripts/svm/executeRebalanceToHubPool.ts, scripts/svm/executeRebalanceToSpokePool.ts, scripts/svm/proposeRebalanceToSpokePool.ts, scripts/svm/remoteHubPoolPauseDeposits.ts, scripts/svm/remoteHubPoolSetDepositRoute.ts, scripts/svm/remotePauseDeposits.ts, scripts/svm/utils/helpers.ts
Standardizes environment variables for EVM chain provider URL and signer mnemonics used in scripts.
Fixes: https://linear.app/uma/issue/ACX-3482/replace-ethers-mnemonic-ethers-provider-url-in-scripts-with-a
=> fix: standardize evm env in scripts

contracts/libraries/PeripherySigningLib.sol
Aligns EIP-712 typed data hashes with spec and client libs like ethers and viem
=> fix: eip712 types and hashes

storage-layouts/AlephZero_SpokePool.json, storage-layouts/PolygonZkEVM_SpokePool.json, storage-layouts/Redstone_SpokePool.json, storage-layouts/Scroll_SpokePool.json, storage-layouts/WorldChain_SpokePool.json, storage-layouts/Zora_SpokePool.json
This PR outdated storage layouts within a number of files on the svm-dev branch.
=> fix: Address Storage layout issue in CI

test/svm/SvmSpoke.HandleReceiveMessage.ts
Since CCTP messenger upgrade on mainnet that we are forking in tests, one of them started failing due to changed seed derivation for `usedNonces` account. Instead of trying to manually derive its address the fix fetches it using the `get_nonce_pda` instruction that has updated with the correct seed derivation.
=> fix(svm): cctp used nonces in tests

programs/multicall-handler/src/lib.rs, programs/svm-spoke/src/common/mod.rs, programs/svm-spoke/src/common/relay_data.rs, programs/svm-spoke/src/constraints.rs, programs/svm-spoke/src/event.rs, programs/svm-spoke/src/instructions/deposit.rs, programs/svm-spoke/src/instructions/fill.rs, programs/svm-spoke/src/instructions/slow_fill.rs, programs/svm-spoke/src/instructions/token_bridge.rs, programs/svm-spoke/src/lib.rs, programs/svm-spoke/src/state/instruction_params.rs, programs/svm-spoke/src/state/state.rs, programs/svm-spoke/src/utils/merkle_proof_utils.rs, programs/svm-spoke/src/utils/message_utils.rs, scripts/svm/fakeFillWithRandomDistribution.ts, src/svm/instructionParamsUtils.ts, src/types/svm.ts, test/svm/SvmSpoke.Fill.AcrossPlus.ts, test/svm/SvmSpoke.SlowFill.AcrossPlus.ts
Signed-off-by: Chris Maree <christopher.maree@gmail.com>
=> Feat: remove more v3 refrences

deploy/consts.ts, utils/constants.ts
This information has been upstreamed to the constants repo, so just unpack it here.
=> refactor(consts): Autopopulate CCTP domain IDs

package.json, tasks/enableL1TokenAcrossEcosystem.ts, utils/constants.ts, yarn.lock
=> chore: Bump constants & update enable token script

.github/workflows/publish.yml, package.json
Trying to resolve the issue posting compiled SVM binaries on GitHub releases
=> fix: content permissions in release

tasks/enableL1TokenAcrossEcosystem.ts
- Add World Chain to v4 SpokePools (in anticipation of upgrade).
- Fix disabling token routes (must be lower case).
=> chore: Update depositRoutes script

contracts/test/MockOFTMessenger.sol, foundry.toml, package.json, test/evm/foundry/fork/UniversalAdapterOFT.t.sol, test/evm/foundry/local/Universal_Adapter.t.sol, test/evm/foundry/local/Universal_SpokePool.t.sol, test/evm/hardhat/chain-adapters/Arbitrum_Adapter.ts, test/evm/hardhat/chain-specific-spokepools/Arbitrum_SpokePool.ts
Note: addressed these 2 points:
- New additions only add 5 single positive overall cases to the suite, leaving many other edge cases untested and not asserting any negative situations.
- The values used for testing the outgoing fees have been [set to zero](https://github.com/across-protocol/contracts/blob/c5d7541037d19053ce2106583b1b711037483038/test/evm/foundry/local/Universal_Adapter.t.sol#L291), as a result of which the whole fee protection is bypassed.
Added multiple new local(unit) test-cases (fee ones were added in [M-03 PR](https://github.com/across-protocol/contracts/pull/1029)) as well as a fork test for sending `USDT` via a `Universal_Adapter`.
A fork test can be run with this command: `NODE_URL_1=<your-ethereum-rpc-url> forge test --match-path …
=> [M-04] Insufficient Test Coverage

script/utils/constants.json
It was accidentally removed in this pr: https://github.com/across-protocol/contracts/pull/1106
Will be adding the script to generate this file in pre-commit hook in a follow up pr
=> chore: Added back constants json

hardhat.config.ts, package.json, scripts/deployMultisig.ts, utils/index.ts, utils/network.ts, yarn.lock
Required to have safe deployed when using the UniversalSpokePool which is an ownable contract.
Note that this script will deploy the safe at a new address than the existing safe's because the salt nonce is set differently from whatever the Safe UI uses.
=> feat: Add deploy Safe script
