contracts/HubPool.sol
contracts/MerkleLib.sol
contracts/SpokePool.sol

Note: the proof verification functions all return true for now to make interacting with them simpler until we have some js or ts that can be used to construct them.

feat: add a first draft of the proof library

---

contracts/HubPool.sol
contracts/MerkleLib.sol
test/HubPool.Fixture.ts
test/HubPool.RelayerRefund.ts
test/constants.ts
test/utils.ts

This PR adds the second iteration of `initiateRelayerRefund`, `disputeRelayerRefund` and `executeRelayerRefund`.

feat(HubPool): Second iteration on init, dispute and execute relayer refund bundles

---

test/HubPool.Admin.ts
test/HubPool.Fixture.ts
test/HubPool.LiquidityProvision.ts
test/HubPool.RelayerRefund.ts
test/SpokePool.Admin.ts
test/SpokePool.Deposit.ts
test/SpokePool.Fixture.ts
test/SpokePool.Relay.ts
test/utils.ts

This PR is just a simple refactor that moves the existing test deployment logic to using hardhat fixtures, which is the recommended way to "snapshot" deployments in tests.
I ran an a/b test on these (and ensured that all conditions were the same, like contracts were already compiled, etc). We saw a pretty decent test speedup from 16s to 12s (25%-ish). This is pretty small, and as long as the repo and tests stay simple and small this will be insignificant, but still good to know that it didn't slow things down :).
Note: this also includes one or two `any`s that I saw an opportunity to replace with something more specific.

improve: move all tests to hardhat fixtures

---

contracts/SpokePool.sol
test/SpokePool.Fixture.ts
test/SpokePool.Relay.ts

In the past, emitting a complex object in an event causes Etherscan difficulty in decoding the params. We should emit all neccessary params individually.

improve: Destructure RelayData params in FilledRelay event

---

.github/workflows/publish.yml

Just adds a simple config using github's recommended process whereby it publishes when you create a release on the github UI.

feat: add release process via github actions

---

contracts/HubPool.sol
contracts/HubPoolInterface.sol
contracts/MerkleLib.sol
contracts/Optimism_SpokePool.sol
contracts/SpokePool.sol
contracts/SpokePoolInterface.sol
contracts/test/MerkleLibTest.sol
contracts/test/MockSpokePool.sol
package.json
test/HubPool.Admin.ts
test/HubPool.Fees.ts
test/HubPool.Fixture.ts
test/HubPool.LiquidityProvisionFees.ts
test/HubPool.PooledTokenSynchronization.ts
test/HubPool.RefundExecution.ts
test/HubPool.RefundInitilization.ts
test/HubPool.RelayerDispute.ts
test/MerkleLib.Proofs.ts
test/MerkleLib.utils.ts
test/SpokePool.RefundExecution.ts
test/SpokePool.RefundInitialization.ts
test/SpokePool.SlowRelay.ts
test/constants.ts
test/utils.ts
utils/MerkleTree.ts

This doesn't include tests or some of the meat of the verification and fill logic just to allow us to agree on the interfaces before moving forward.

feat: add slow relay functionality

---

contracts/Optimism_SpokePool.sol
contracts/SpokePool.sol
contracts/SpokePoolInterface.sol
contracts/test/MockSpokePool.sol
hardhat.config.ts
package.json
test/HubPool.Fixture.ts
test/MerkleLib.Proofs.ts
test/SpokePool.Deposit.ts
test/SpokePool.Fixture.ts
test/SpokePool.Relay.ts
test/SpokePool.SlowRelay.ts
test/chain-adapters/Arbitrum_Adapter.ts

Percentages and timestamp-based variables can be smaller size to save gas costs for storing data

feat(spoke-pool): Reduce size of state variables

---

contracts/HubPool.sol
test/HubPool.PooledTokenSynchronization.ts
test/gas-analytics/HubPool.RefundExecution.ts

Fixes a bug where the bond can be attributed to repayments instead of reserved for the proposer.

fix: take bond into account when syncing

---

contracts/SpokePool.sol
test/SpokePool.Relay.ts

Adds convenience method that depositor can submit to signal to relayers that they can use an updated relayer fee. Reuses the same logic that is used in the fillRelayWithUpdatedFee that relayers use to submit a relay with an updated fee.
﻿Signed-off-by: nicholaspai <npai.nyc@gmail.com>

 feat(spoke-pool): Add speedUpDeposit method

---

contracts/HubPool.sol
contracts/HubPoolInterface.sol
test/HubPool.Admin.ts

Max leaf count can only be uint8 to be consistent with size of `RootBundle.claimedBitMap` and is the same size passed into `proposeRootBundle`, so this is likely just fixing a mistake.

improve: Change pool rebalance leaf count type to uint8

---

contracts/HubPool.sol
contracts/SpokePool.sol
package.json

update events after internal chat

---

contracts/chain-adapters/Optimism_Adapter.sol

To fully support optimism we need some additional branching logic to change out the bridge address when bridging tokens that require custom bridges. To start with, this includes DAI and SNX.

fix(optimism-adapter): handle custom bridges

---

contracts/SpokePool.sol
test/SpokePool.Relay.ts
test/SpokePool.SlowRelay.ts

To reduce expected client event queries, overload the `FilledRelay` event to indicate both Slow and Fast relays. Add an `isSlowRelay` param to the event to clearly indicate whether a relay is slow or not. Currently the `repaymentChainId` is also set to 0 to indicate a slow relay but this PR allows for the possibility for the slow relayer to indicate a chain to be repaid on.

improve: Add isSlowRelay param to FilledRelay event

---

contracts/HubPool.sol
test/HubPool.DisputeRootBundle.ts
test/fixtures/UmaEcosystem.Fixture.ts

Root bundle data can be grabbed deterministically by looking up the latest `ProposeRootBundle` event before the `DisputeRootBundle` event, so some of the ancillary data currently emitted by the HubPool is redundant.
The reason why we assume that voters will have to fetch a `ProposeRootBundle` event is that  the root bundle's `blockEvaluationNumbers` are not stored on-chain. If they were stored on-chain, we could emit all of the data necessary to evaluate a dispute in the ancillary data. But since `blockEvaluationNumbers` are not stored-onchain, voters will have to look up the `ProposeRootBundle` event regardless and therefore we should not expend gas emitting data already included in that event.

improve: Simplify ancillary data

---

contracts/HubPool.sol
contracts/MerkleLib.sol
contracts/PolygonTokenBridger.sol
contracts/Polygon_SpokePool.sol
contracts/SpokePool.sol
contracts/test/MerkleLibTest.sol
test/HubPool.Admin.ts
test/HubPool.ProtocolFees.ts
test/MerkleLib.Claims.ts
test/SpokePool.Relay.ts

Issue:
- [L02] Lack of input validation
- Throughout the codebase there are functions lacking sufficient input validation. For instance:
- In the HubPool contract the various admin functions will accept 0 values for inputs. This could
result in the loss of funds and unexpected behaviors if null values are unintentionally provided.
- In the HubPool contract the setProtocolFeeCapture function does not use the
noActiveRequests modifier. This could allow the protocol fee to be increased even for liquidity
providers that have already provided liquidity.
- In the MerkleLib library the isClaimed1D function does not work as expected if an index is
greater than 255. In such a case, it will return true despite the fact that those values are not
actually claimed.
- In the SpokePool contract the …

improve: [L02] validate function inputs

---

contracts/HubPool.sol
test/HubPool.Admin.ts

Issue:
- [L05] Liquidity provisioning can skew fee assessments
- In the HubPool contract the enableL1TokenForLiquidityProvision function allows the contract
owner to enable an l1token to be added to the protocol for liquidity pooling.
- This is allowed even if the l1token is already currently enabled.
- As this function also sets the lastLpFeeUpdate variable to the then-current block.timestamp,
enabling an already enabled token will skip over the period of time since lastLpFeeUpdate was last
set. As a result, any LP fees that should have been assessed for that time period would simply never be
assessed.
- Consider reverting if this function is called for an l1token that is already enabled.
Solution:
- Only set `lastLpFeeUpdate` upon first enabling

fix: [L05] Enabling token for Liquidity provisioning should not reset lastLpFeeUpdate

---

contracts/chain-adapters/Ethereum_Adapter.sol

Issue:
- [N01] Missing link to referenced code
- Within the Ethereum_Adapter, there is a mention of copying code from "Governor.sol". It appears that
the contract in question is Governor.sol from the UMAprotocol/protocol repository.
- Since it is a part of a separate repository, and it is possible that the code may change in the future,
consider including a link to the file, including a commit hash, so that it can be easily referenced by
developers and reviewers in the future.﻿

feat: [N01] Add source for _executeCall implementation

---

contracts/HubPool.sol
test/HubPool.Admin.ts
test/HubPool.ExecuteRootBundle.ts

#91 removed checks that `adapter != address(0)` because I erroneously assumed that `address(0).delegatecall` would revert this. This PR re-adds the checks + adds unit tests

fix: [L02] Re-add checks that adapter is not 0x0

---

contracts/HubPool.sol
test/HubPool.Admin.ts
test/HubPool.DisputeRootBundle.ts
test/HubPool.ProposeRootBundle.ts

Issue:
- [L07] Unexpected proposal cancellation
- In the HubPool contract during a call to the disputeRootBundle function, if the bondAmount and
finalFee values are the same, then the proposer bond passed to the optimistic oracle is zero.
When this happens, the optimistic oracle unilaterally sets the bond to the finalFee and then attempts
to withdraw bond + final fee.
- Since the HubPool only sets the allowance for the oracle to bondAmount rather than bondAmount +
finalFee, this transfer will fail and, as a result, the proposal will be cancelled.
- This means that in the situation where bondAmount and finalFee values are identical, every proposal
will be cancelled. Consider documenting this situation, checking for it explicitly and reverting with an
insightful error message. Additionally, …

improve: [L07] Prevent unexpected proposal cancellations by constraining bond size

---

contracts/LpTokenFactory.sol

**Problem:**
When the LpTokenFactory contract creates an ExpandedERC20 token contract, the factory becomes
the owner of that token contract. The factory then proceeds to assign the minter and burner roles to
the msg.sender. The factory remains the owner.
**Solution:**
Set associated roles and transfer ownership to the HubPool.

fix[N11] Fix Residual privleged roles

---

contracts/HubPool.sol
contracts/HubPoolInterface.sol
contracts/MerkleLib.sol
contracts/SpokePoolInterface.sol

**Problem**:
Although most of the codebase is thoroughly documented, there are a few instances where
documentation is lacking. For instance:
In the HubPool contract the public unclaimedAccumulatedProtocolFees variable has no inline
documentation.
In the HubPool contract the inline documentation accompanying
PoolRebalanceLeaf.netSendAmounts, although lengthy, could benefit from additional
clarification around the case of negative values. It could clarify further that in such cases the
actual netSendAmounts value is ignored, but it should match the amountToReturn parameter in
the RelayerRefundLeaf.
Many of the functions in the MerkleLib library are missing NatSpec @return statements.
**Solution**: all places with missing documentation were updated.

fix[N04] Add additional documentation

---

contracts/Arbitrum_SpokePool.sol
contracts/Ethereum_SpokePool.sol
contracts/HubPoolInterface.sol
contracts/MerkleLib.sol
contracts/Optimism_SpokePool.sol
contracts/PolygonTokenBridger.sol
contracts/Polygon_SpokePool.sol
contracts/SpokePool.sol
contracts/chain-adapters/Arbitrum_Adapter.sol
contracts/chain-adapters/Ethereum_Adapter.sol
contracts/chain-adapters/Polygon_Adapter.sol
contracts/interfaces/LpTokenFactoryInterface.sol

**Problem**:
The below list outlines contract import statements that are unnecessary:
The WETH9 and Lockable imports are not used in the Ethereum_Adapter contract.
The CrossDomainEnabled, IL1StandardBridge, and Lockable imports are not used in the
Polygon_Adapter contract.
The WETH9 and IERC20 imports are not used in the Arbitrum_Adapter contract.
The AdapterInterface interface is imported twice in the Arbitrum_Adapter contract.
The WETH9 and SpokePoolInterface imports are not used in the Ethereum_SpokePool contract.
The IERC20 import in the LpTokenFactoryInterface interface is unused.
The MerkleLib is imported twice in the SpokePool contract.
**Solution**
Removed unnecessary imports. I also changed the ordering of some of them to be more consistant (implementation, then interfaces, then …

fix[N15] Unnecessary import statements

---

contracts/LpTokenFactory.sol
test/HubPool.Admin.ts

**Problem:**
In the LpTokenFactory contract, the LP tokens it creates have inconsistent versioning in their
metadata.
While the token symbol is prepended with Av2 (ostensibly for "Across version 2"), the token name is
prepended only with "Across" and no version number.
**Resolution:**
LP token name now contains the version, like the symbol.

fix[N03] Fixed inconsistant token metadata versioning

---

contracts/HubPool.sol
contracts/HubPoolInterface.sol
test/HubPool.DisputeRootBundle.ts
test/gas-analytics/HubPool.RootExecution.ts
test/gas-analytics/SpokePool.RelayerRefundRootExecution.ts

Ancillary data is the empty string so we can remove the helper function + reduce emitted event params to save gas. disputeRootBundle gas reduced by ~1000 (0.3%).

improve: Remove ancillary data helper function

---

contracts/PolygonTokenBridger.sol
deploy/008_deploy_polygon_token_bridger_mainnet.ts
deploy/010_deploy_polygon_token_bridger_polygon.ts
deploy/consts.ts
test/chain-specific-spokepools/Polygon_SpokePool.ts

**Problem:**
The PolygonTokenBridger contract's primary functions are only intended to be called either on l1 or
l2, but not both. In fact, calling the functions on the wrong chain could result in unexpected behavior
and unnecessary confusion.
In the best case, the functions will simply revert if called from the wrong chain because they will
attempt to interact with other contracts that do not exist on that chain. For example, calling the
receive function (by sending the contract some native asset) could trigger reverts on Polygon, but not
on Ethereum, because there is a WETH contract at the l1Weth address on the latter but not the former.
However, in the worst case, it is possible that such calls will not revert, but result in lost funds instead.
For example, if a WETH-like contract was …

fix[L04] Enforce chainId requirements in PolygonTokenBridger

---

hardhat.config.ts

8.13 [release notes](https://blog.soliditylang.org/2022/03/16/solidity-0.8.13-release-announcement/)
Empirically, gas costs are not really affected.﻿

improve: Update solc version to 8.13

---

contracts/RateModelStore.sol

We need the rate model store from across V1. This PR simply copy and pastes this contract with no changes other than one modification to an import.

feat: Added rate model store from across v1

---

contracts/HubPool.sol
contracts/SpokePool.sol

Dataworker will compute roots for a given bundle block range and look up `SpokePool.RelayedRootBundle` events with matching roots, so we should index on those roots.
Additionally, the HubPool's `ProposeRootBundle` event doesn't need to index any of the root hashes. If anything, it should index the `bundleBlockRange` which is the key for the dataworker to reconstruct roots, but even this might be unneccessary.

improve: Change indexed event params to assist offchain dataworker

---

contracts/HubPool.sol

OZ points out that using the `transfer` pattern, introduced in PR: https://github.com/across-protocol/contracts-v2/pull/90 is not optimal as if the target of the eth needs more than 2300 gas the tx will revert. This PR changes this to use the `Address.sendValue` function, which uses the `.call` pattern under the hood to address this.

fix:M03 Move to using address.sendValue over the transfer pattern when sending eth

---

contracts/SpokePool.sol

EIP1271 is mistakenly referred to as EIP191 in the contracts﻿

fix: Change mentions of EIP191 --> EIP1271

---

contracts/HubPool.sol

`poolRebalanceLeafCount` is `uint8` in the contract but not the same in the event emitted.

fix: Change event param type to match variable

---

contracts/HubPool.sol

AncillaryData import no longer needed since PR #114 removed logic to construct ancillary data using this lib

refactor: Remove AncillaryData import from HubPool

---

contracts/HubPool.sol
contracts/SpokePool.sol

Leaving the counter `i` variable as `uint256` removes gas cost to cast to `uint32` and also prevents chance that leaf count will cause overflow, which is a risk with the increment logic `++i` being inside an `unchecked` block.﻿

improve: Reduce gas and minimize overflow risk in for loops

---

package.json
test/MerkleLib.Proofs.ts
utils/MerkleTree.ts

Clients that import the MekrleLib module should have universal way to detect if tree is empty and handle accordingly.
﻿Signed-off-by: nicholaspai <npai.nyc@gmail.com>

improve: Add EMPTY_ROOT constant and isEmpty functions to MerkleRoot utils

---

tasks/enableL1TokenAcrossEcosystem.ts
tasks/utils.ts

Arbitrum requires an additional admin call to set up when enabling a token. This PR addresses this.

fix: add additional admin calls for arbitrum to token enable script

---

contracts/HubPool.sol
contracts/HubPoolInterface.sol
test/HubPool.LiquidityProvision.ts
test/HubPool.LiquidityProvisionHaircut.ts
test/HubPool.ProposeRootBundle.ts

- Adds untested haircut logic that can scale the exchangeRateCurrent by some haircut amount, in the event of protocol loss of funds.
- Adds the ability to pause the addition/removal of liquidity. should be used in conjunction with haircutting to stop LPs from getting the wrong rate until the hair cut is done.

fix: add haircut proposal

---

contracts/HubPool.sol

There are 3 typos identified in the `HubPool` contracts. This PR fixes them.

fix: address typos in hubpool

---

contracts/chain-adapters/Arbitrum_RescueAdapter.sol

This contract can be deployed to rescue ETH from the aliased HubPool address on Arbitrum﻿

feat: Arbitrum_RescueAdapter

---

contracts/chain-adapters/Ethereum_RescueAdapter.sol

This adapter is meant to rescue funds from a malfunctioning, broken, or misconfigured HubPool.

feat: add ethereum rescue adapter

---

contracts/chain-adapters/Arbitrum_RescueAdapter.sol
contracts/chain-adapters/Arbitrum_SendTokensAdapter.sol
test/chain-adapters/Arbitrum_SendTokensAdapter.ts

Adapter can be used to send funds from HubPool to SpokePool via emergency admin action. Admin can atomically (1) change Arbitrum adapter to this one, (2) send multiple ERC20's out of HubPool balance, (3) reset Arbitrum adapter.﻿

feat: Add Arbitrum_SendTokensAdapter

---

contracts/chain-adapters/Arbitrum_Adapter.sol
contracts/test/ArbitrumMocks.sol
test/chain-adapters/Arbitrum_Adapter.ts

This [merged PR](https://github.com/OffchainLabs/arbitrum/pull/2107) is now live for most Arbitrum ERC20 gateways (except DAI), so we can use the new function outboundTransferCustomRefund to receive refunds at an EOA we control instead of the [aliased hub pool address](https://arbiscan.io/address/0xd297fa914353c44b2e33ebe05f21846f1048cfeb), which is the L1 sender of the tokens technically.

improve(arbitrum-adapter): Use outboundTransferCustomRefund when sending tokens to L2

---

package.json
scripts/zkSync.ts
yarn.lock

We don't use zksync-web3 since we use the hardhat-deploy plugin's native support for zksync

chore: remove zksync-web3 from dependencies

---

contracts/merkle-distributor/MerkleDistributor.sol
test/merkle-distributor/MerkleDistributor.ts

I discovered this by while working on this [PR](https://github.com/across-protocol/across-token/pull/32/files) for the exact test case I've included. The problem arises when all of the claims _for different window indices_ are for the same token and recipient. If this `if` statement [here](https://github.com/across-protocol/contracts-v2/blob/f42e843e351d70692bd8575a44d0f563d1920d8b/contracts/merkle-distributor/MerkleDistributor.sol#L159) is not triggered, then `batchedAmount` accumulates the amount for each claim. It only gets decremented from a window's `remainingAmount` once the if statement is entered, which is either:
- On the last claim
- When the reward token changes between claims
- When the account changes between claims
If the reward token and account do not change, then its …

fix: Fix bug in MerkleDistributor that doesn't decrement remainingAmount for merkle windows correctly

---

package.json
test/merkle-distributor/MerkleDistributor.ts
yarn.lock

Should import from @uma/common instead of no longer maintained @uma/merkle-distributor

chore: Update MerkleTree import

---

contracts/SpokePool.sol
test/fixtures/SpokePool.Fixture.ts

Upon redeployment of SpokePool may be helpful to avoid signature collisions

improve: Update speed up signature 

---

contracts/Arbitrum_SpokePool.sol
contracts/Boba_SpokePool.sol
contracts/Ethereum_SpokePool.sol
contracts/Optimism_SpokePool.sol
contracts/Ovm_SpokePool.sol
contracts/Polygon_SpokePool.sol
contracts/SpokePool.sol
contracts/ZkSync_SpokePool.sol
contracts/test/MockSpokePool.sol
test/SpokePool.Admin.ts
test/chain-specific-spokepools/Arbitrum_SpokePool.ts
test/chain-specific-spokepools/Ethereum_SpokePool.ts
test/chain-specific-spokepools/Optimism_SpokePool.ts
test/chain-specific-spokepools/Polygon_SpokePool.ts
test/fixtures/HubPool.Fixture.ts
test/fixtures/SpokePool.Fixture.ts
test/gas-analytics/HubPool.RootExecution.ts

Constructor should be able to initialize deposit ID to support upgrades
The alternative implementation with less code diff would be to add an admin function `incrementDepositCount(uint32 count)` where the admin could increase the deposit count. I don't see this being useful outside of upgrades so I decided not to do it. 
Thoughts?

feat(SpokePool): Initialize depositId

---

contracts/SpokePool.sol
contracts/test/MockERC1271.sol
test/SpokePool.Relay.ts
test/fixtures/SpokePool.Fixture.ts

Closes ACX-584
As noted by @nicholaspai: _This does open the possibility that someone could forge an EIP1271 signature and set the relayer fee to 50%, and then relay the honest depositor's deposit, stealing ~50% of the total deposit. We should comment on this and debate whether this risk is worth it_

feat: support erc1271 for verifying relay fee update sigs

---

contracts/Ovm_SpokePool.sol
contracts/SpokePool.sol
contracts/upgradeable/EIP712CrossChainUpgradeable.sol
contracts/upgradeable/MultiCallerUpgradeable.sol
contracts/upgradeable/TestableUpgradeable.sol

Makes it more obvious that __gap should always be at end of contract storage.

improve: move __gap to bottom of contracts

---

contracts/MerkleLib.sol
contracts/Ovm_SpokePool.sol
contracts/Polygon_SpokePool.sol
contracts/SpokePool.sol
contracts/SpokePoolInterface.sol
contracts/test/MerkleLibTest.sol
hardhat.config.ts
package.json
test/MerkleLib.Proofs.ts
test/MerkleLib.utils.ts
test/SpokePool.Deposit.ts
test/SpokePool.Relay.ts
test/SpokePool.SlowRelay.ts
test/constants.ts
test/fixtures/SpokePool.Fixture.ts
test/gas-analytics/SpokePool.SlowRelayLeafExecution.ts
test/gas-analytics/utils.ts
test/utils.ts
yarn.lock

This modifies the SpokePool to support incentives to move tokens to other chains. This is done by establishing a defined ordering of deposits and fills on each chain and rewarding depositors and relayers for moving the tokens towards the right running balance.
Specific changes:
- To avoid frontrunning and allow depositors and relayers to lock in their reward, a running count of the aggregate amount of funds is tracked for both deposits and fills. Depositors and relayers can then pass in a maxCount to cap the amount of capital coming in ahead of them that they did not anticipate.
- Both LP fees and relayer fees can now be negative.
- The slow fill process/struct includes a new value, called payoutAdjustment. This enables the fees/rewards that would typically be passed on to a relayer to be …

feat: universal bridge adapter

---

contracts/SpokePool.sol

Several instances of docstrings or comments in the codebase were found to be erroneous. In
particular:
- In the SpokePool contract's `_fillRelay` function, the comment on line 1003
appears unrelated to the if statement on the following line. Consider revising the
comment.
- The docstring for `pauseDeposits` in the SpokePool contract says it "pauses deposit
and fill functions", but pausing fill functions is performed by calling `pauseFills` , which
does not have a docstring.
Consider revising the `pauseDeposits` docstring and adding a docstring to `pauseFills`.

improve: [L-01] Incorrect or misleading documentation

---

contracts/Polygon_SpokePool.sol
contracts/Succinct_SpokePool.sol

The `setSuccinctTargetAmb` administrative function does not emit a relevant event after changing the `succinctTargetAmb` address.
Consider always emitting events after sensitive changes take place to facilitate tracking and notify off-chain clients that follow the protocol's contracts' activity.
This PR not only addresses the above issue but adds events to the `Polygon_SpokePool` and `Succinct_SpokePool`'s handler functions that trigger when they are called by an L2 system contract to finalize an L1-->L2 message

improve: [L02] Lack of event emission after sensitive action

---

contracts/Polygon_SpokePool.sol
contracts/SpokePool.sol
contracts/chain-adapters/Arbitrum_Adapter.sol
contracts/chain-adapters/Optimism_Adapter.sol
contracts/chain-adapters/Polygon_Adapter.sol
contracts/interfaces/AdapterInterface.sol
contracts/interfaces/LpTokenFactoryInterface.sol
contracts/interfaces/WETH9Interface.sol

Throughout the codebase, there are several parts that do not have docstrings. In particular:
- AdapterInterface.sol , lines 13-20: the interface functions are undocumented.
AbitrumAdapter.sol , lines 9-54: the ArbitrumL1InboxLike and
ArbitrumL1ERC20GatewayLike interfaces and their functions are undocumented.
- LpTokenFactoryInterface.sol , lines 4-5: the interface and its functions are
undocumented.
- Optimism_Adapter.sol , lines 15-16: the SynthetixBridgeToOptimism interface
and its function are undocumented.
- Polygon_Adapter.sol , lines 10-30: the IRootChainManager ,
- IFxStateSender , and DepositManager interfaces and their functions are
undocumented.
- Polygon_SpokePool.sol , line 11: the processMessageFromRoot function is
undocumented.
- SpokePool.sol , lines 169-196: the …

improve: [L03] Missing docstrings

---

.eslintignore
.npmignore
.prettierignore
contracts/SpokePool.sol
test/SpokePool.Relay.ts

In the SpokePool contract, the speedUpDeposit function performs the following check on
the updatedRelayerFeePct variable:
require(updatedRelayerFeePct < 0.5e18, "invalid relayer fee");
Unlike the equivalent check in the deposit function, in this case the SignedMath.abs
function is not used, which allows the updatedRelayerFeePct value to reach or go below
the lower limit of -0.5e18 . An attempt by the relayer to fill this request will be rejected by the
_fillRelay function's fee check.
Consider using the SignedMath.abs function to ensure the updatedRelayerFeePct
argument provided to speedUpDeposit is within the expected limits.

fix: [L04] updatedRelayerFeePct can be lower than expected

---

contracts/Succinct_SpokePool.sol
test/chain-specific-spokepools/Succinct_SpokePool.ts

There is a require statement with multiple conditions in the handleTelepathy function of
the Succinct_SpokePool contract.
Consider isolating each condition in its own separate require statement with a corresponding
error message, to more easily identify the specific condition that failed.
This change allowed me to make unit tests for `Succinct_SpokePool` more strict and check error messages

improve: [N02] Multiple conditions in a single require statement

---

contracts/MerkleLib.sol

The setClaimed1D function in MerkleLib.sol performs a modulo 256 operation on
index to yield a result in the range [0, 255]. However, index is a uint8 variable, so the
operation index % 256 is equivalent to index .
Consider removing the redundant modulo operation.

improve: [N05] Unecessary modulo operation

---

contracts/Ovm_SpokePool.sol

The _bridgeTokensToHubPool function in the Ovm_SpokePool contract contains two
hard-coded addresses that are not explicitly documented.
Consider creating constants to store these values, and assigning them descriptive variable
names.

improve: [N07] Use of hard-coded values

---

contracts/SpokePool.sol

Stack-related concerns are hopefully mitigated by the recent use of an IR during contract compilation.

improve(SpokePool): Emit FundsDeposited event directly

---

contracts/SpokePool.sol
test/SpokePool.SlowRelay.ts

There was one major issue and a related minor issue discovered around how payoutAdjustmentPct was handled:
1.  In the case where there is a slow fill on a deposit with a negative LP fee, the maxSendAmount passed into the _fillRelay function could cause fillAmountPreFees to be less than the amount, which means it could be less than amountRemainingInRelay. In this case, two errors would occur: a) the slow fill would not complete the fill and b) the payoutAdjustmentPct would be ignored because it is inside the if statement comparing fillAmountPreFees to amountRemainingInRelay.
2. The payoutAdjustmentPct could be set arbitrarily high, potentially causing math overflows. Note: I don't think this would cause any mathematical _errors_ but it could certainly trigger cryptic overflows.
To fix …

fix: fix potential underpayment in slow fill with negative LP fees

---

contracts/SpokePool.sol
contracts/chain-adapters/Polygon_Adapter.sol

- In Polygon_Adapter.sol, the user parameter for the depositEtherFor function is documented using "@dev" instead of "@param user".
- In SpokePool.sol, within the RelayExecution struct's relay parameter description, "parametersin" should be "parameters in".
- In SpokePool.sol, the RelayExecution struct's docstring for parameter payoutAdjustmentPct lists it as "payoutAdjustment".

improve(docstrings): Follow up fixes

---

contracts/SpokePool.sol
test/SpokePool.Relay.ts

Rounding errors are possible when computing `fillAmountPreFees` and we want to enforce that the error is considered in `amountToSend` both to partial and full fills. Currently `amountToSend` is only reset to its postFee amount for situations where `maxTokensToSend > amountRemainingInRelay` which is often the case for slow fills. We should apply the error consistently regardless of the type of fill.

improve(SpokePool): Apply rounding consistently to partial and full fills

---

contracts/SpokePool.sol
test/SpokePool.Relay.ts

When sped up, updated message and recipient are not used

fix: Execute fill with updated message and recipient

---

contracts/SpokePool.sol
contracts/test/AcrossMessageHandlerMock.sol
test/SpokePool.Relay.ts

Allow recipient to handle cases where a deposit with a message is sent in multiple partial fills, by different relayers.
Y

improve(SpokePool): Pass fillCompleted and relayer to acrossMessageHandler

---

deploy/001_deploy_hubpool.ts
deploy/002_deploy_optimism_adapter.ts
deploy/003_deploy_optimism_spokepool.ts
deploy/004_deploy_arbitrum_adapter.ts
deploy/005_deploy_arbitrum_spokepool.ts
deploy/006_deploy_ethereum_adapter.ts
deploy/007_deploy_ethereum_spokepool.ts
deploy/008_deploy_polygon_token_bridger_mainnet.ts
deploy/009_deploy_polygon_adapter.ts
deploy/010_deploy_polygon_token_bridger_polygon.ts
deploy/011_deploy_polygon_spokepool.ts
deploy/012_deploy_boba_adapter.ts
deploy/013_deploy_boba_spokepool.ts
deploy/014_deploy_config_store.ts
deploy/015_deploy_zksync_adapter.ts
deploy/016_deploy_zksync_spokepool.ts
deploy/017_deploy_ethereum_merkle_distributor.ts
deploy/018_deploy_arbitrum_rescueadapter.ts
deploy/019_deploy_bond_token.ts
deploy/020_deploy_arbitrum_sendtoken_adapter.ts
deploy/021_deploy_erc1155.ts
deploy/022_upgrade_spokepool.ts
package.json
test/fixtures/MerkleLib.Fixture.ts
utils/utils.ts

The HRE should only be constructed once, and for the deploy scripts we should try to load that existing object

feat: Remove direct "hardhat" imports, update types in deploy/ scripts

---

test/MerkleLib.utils.ts

Post-UBA, runningBalances will be 2x the length of the other arrays. To avoid having to teach contacts-v2 about ConfigStore versioning, just loosen the constraints to permit pre- and post-UBA formats.
Fixes ACX-1136

feat(UBA): Support UBA pool rebalance leaves in utils

---

package.json

Necessary for UBA work in relayer-v2.

chore: Bump patch level

---

scripts/mintERC1155.ts

Adds check to mint script to skip addresses that already have received a token

feat(erc1155): harden script to only mint to recipients with balance 0

---

contracts/SpokePoolVerifier.sol

This adds a docstring to the deposit method on the SpokePoolVerifier contract.

fix: [N02] Add docstring

---

contracts/HubPool.sol
hardhat.config.ts
package.json
yarn.lock

Bumping to get versions including this commit:
https://github.com/UMAprotocol/protocol/commit/0c97801bf75f6546532402873d02e7cab0821bd5
With this, we no longer import hardhat-etherscan from UMA packages and can proceed with defining an Etherscan config for sepolia in hardhat.config.ts.
Due to code re-org in @uma/core it was necessary to adjust some HubPool.sol imports.

chore: Bump UMA packages

---

.solhint.json
contracts/chain-adapters/ZkSync_Adapter.sol

This PR adds a proxy contract that could be used to bypass zk sync deposit limits by address. To allow for this proxy to be swapped out, the ETH sending address was separated from the address used to send contract calls, so one could be swapped out without affecting the other.

fix: [M-01] zkSync limits

---

contracts/chain-adapters/ZkSync_Adapter.sol
deploy/015_deploy_zksync_adapter.ts
test/chain-adapters/ZkSync_Adapter.ts

This PR removes the hardcoded refund address for zkSync, replaces it with an immutable value, and adds a default address in the deployment script that is the most common dataworker address.

fix: [N-03] Lack of Documentation (removed hardcoded refund address)

---

contracts/chain-adapters/ZkSync_Adapter.sol

Testing on the era testnet shows that typical messaging consumes up around 1M gas on L2.
This limit may change, subject to further testing.

fix: Bump L2 gas limit for L1 -> L2 zkSync messages

---

deploy/003_deploy_optimism_spokepool.ts
deploy/005_deploy_arbitrum_spokepool.ts
deploy/007_deploy_ethereum_spokepool.ts
deploy/011_deploy_polygon_spokepool.ts
deploy/013_deploy_boba_spokepool.ts
hardhat.config.ts
utils/utils.hre.ts

The Ethereum SpokePool deployment script relies on companionNetworks being defined in order to resolve the HubPool and WETH contract addresses. This does unfortunately create a circular reference, but it permits deployment and I haven't seen any negative side-effects.
Additionally, the other SpokePool deployment scripts incorrectly logged the chain ID for the HubPool deployment. This change now factors out the task of resolving the chain IDs and returns them in an unambiguous form. This also simplifies most of the deployment scripts.

fix: SpokePool deployment script corrections

---

utils/utils.hre.ts

Since migrating to OZ's hardhat-upgrades plugin, deployments are no longer being retained in the deployments directory. Fortunately, it seems possible to do this manually via some of the objects exposed by hre and hardhat-deploy.
This question on StackOverflow arrived at the same conclusion:
https://stackoverflow.com/questions/74870472

fix: Reinstate deployment artifact retention

---

contracts/SpokePool.sol
test/SpokePool.SlowRelay.ts

SlowFill reuses existing _fillRelay logic to fill a slow relay leaf. This function has an early return path where if the msg.sender == recipient, it will exit early to avoid a transfer. This is useful for a 
normal relay where a relayer, relaying to themselves, shouldn't need to send funds to itself. However, for a slow fill, the "relayer" is the contract (i.e. funds are sent out out of the spoke pool rather 
than brought in by the relayer/msg.sender) so we always want to send funds if we're in a slow relay.
Fixes ACX-1394

fix(SpokePool): SlowFill should still transfer if executed by recipient

---

contracts/BondToken.sol

The BondToken contract is basically WETH9, so we inherit its license.

fix: BondToken license

---

test/SpokePool.Deposit.ts
test/fixtures/SpokePool.Fixture.ts

There are many now, so it makes sense to split them apart before adding new ones. While here:
- Enforce that deposits revert for the expected revert reasons.
- Enforce that deposits succeed and emit a "FundsDeposited" event.
- Tweak a utility function for simplicity.
Done in advance of a proposed change to the SpokePool quoteTimestamp validation.

refactor: Split out and improve SpokePool deposit tests

---

contracts/SpokePool.sol
test/SpokePool.Deposit.ts
test/fixtures/SpokePool.Fixture.ts

improve(SpokePool): Prevent future deposit quoteTimestamps
Future quoteTimestamps create unusual challenges for the bots that
process Deposit events. Fundamentally, it's impossible to compute the
correct realizedLpFeePct for a deposit with a future quoteTimestamp, so
all implementations must correctly park these early deposits and pull
them out at the right time. Given that we are now seeing diversity in
relayer implementations, it seems improbable that all will implement
this correctly, and the downside is that they will lose funds for a
slight mistake here.
From the depositor side, for the most part it is hard to justify
deliberately setting a quoteTimestamp that is in the future.
The scenarios where this might impact users is:
- A chain lags slightly behind the current time, meaning …

improve(SpokePool): Prevent future deposit quoteTimestamps

---

contracts/chain-adapters/Arbitrum_Adapter.sol
contracts/chain-adapters/Arbitrum_SendTokensAdapter.sol
deploy/004_deploy_arbitrum_adapter.ts
test/chain-adapters/Arbitrum_Adapter.ts
test/chain-adapters/Arbitrum_SendTokensAdapter.ts

This change was prompted by OZ finding [N-03] on the audit for Across zkSync contracts.

improve: Remove Arbitrum hardcoded refund address

---

contracts/SpokePool.sol
contracts/interfaces/SpokePoolInterface.sol
hardhat.config.ts
test/SpokePool.Deposit.ts

depositNow() is a new deposit() wrapper that removes the need for the caller to supply a quoteTimestamp. Instead, the value of getCurrentTime() is used.
This is introduced to address the issue of multisig depositors having only a narrow window to collect the necessary signatures for a deposit. Instead, LP fee certainty is traded for flexibility around when the deposit is able to be submitted. The depositor is still able to query the expected LP fee via the Across API, so the chance of paying more fees than anticipated is fairly low.
Ref ACX-1544

feat: deposit() wrapper with current quoteTimestamp

---

package.json

Release v2.4.5 was never actually produced, but tag v2.4.5 was accidentally used when producing a draft release.

chore(across-v2): Bump patch level

---

contracts/SpokePool.sol

These checks shouldn't be necessary; it's up to relayer implementations to ensure that they are robust to the input and output token amounts.

refactor(SpokePool): Remove token amount limits on depositUSS()

---

deploy/003_deploy_optimism_spokepool.ts
deploy/005_deploy_arbitrum_spokepool.ts
deploy/007_deploy_ethereum_spokepool.ts
deploy/011_deploy_polygon_spokepool.ts
deploy/013_deploy_boba_spokepool.ts
deploy/025_deploy_base_spokepool.ts
utils/utils.hre.ts

The current references to `deployNewProxy` result in compilation errors. We should modify `deployNewProxy` so that it can pass an initializer & constructor args and call that fn correctly.

fix: use updated deployNewProxy fn

---

contracts/Polygon_SpokePool.sol
contracts/SpokePool.sol
contracts/interfaces/SpokePoolInterface.sol
contracts/test/MockCaller.sol
test/MerkleLib.utils.ts
test/SpokePool.ExecuteRootBundle.ts
test/SpokePool.SlowRelay.ts
test/chain-specific-spokepools/Polygon_SpokePool.ts
test/fixtures/SpokePool.Fixture.ts

Useful safety feature to protect function that can send xchain messages. Also adds useful scaffolding for USS unit tests

feat(SpokePool): Require executeX() caller to be EOA

---

README.md

We should move the `deployed` tag to whichever contract version we end up deploying

improve(README): Add details about deployed contract versions

---

deploy/003_deploy_optimism_spokepool.ts
deploy/005_deploy_arbitrum_spokepool.ts
deploy/007_deploy_ethereum_spokepool.ts
deploy/011_deploy_polygon_spokepool.ts
deploy/013_deploy_boba_spokepool.ts
deploy/016_deploy_zksync_spokepool.ts
deploy/025_deploy_base_spokepool.ts

Spurred by this comment:  https://github.com/across-protocol/contracts-v2/pull/381#discussion_r1437706052 We should comment on all of our spoke deployments.
Alternate option: we immortalize these args in a constant because they're identical across our deploy scripts.

improve(docs): add constructor arg docs to spoke deploy scripts

---

test/MerkleLib.Proofs.ts

These are missing for SlowFill but we should add them for the USS functionality

 improve(tests): Add USSSlowFill MerkleLib unit tests

---

contracts/test/AcrossMessageHandlerMock.sol
contracts/test/MockSpokePool.sol
test/SpokePool.Relay.ts
test/fixtures/SpokePool.Fixture.ts

The internal `_fillRelayUSS` function handles most of the fill logic and this PR adds useful test infrastructure for future testing.
This PR also includes unit testing logic specific to the external `fillUSSRelay` function

improve: Unit tests for _fillRelayUSS() internal logic and fillRelayUSS() external function

---

contracts/Polygon_SpokePool.sol
contracts/SpokePool.sol
contracts/interfaces/USSSpokePoolInterface.sol
contracts/test/AcrossMessageHandlerMock.sol
contracts/test/MockSpokePool.sol
test/SpokePool.Deposit.ts
test/SpokePool.Relay.ts
test/fixtures/SpokePool.Fixture.ts

Fixes bug in _verifyUpdateUSSDepositMessage where the incorrect type string is used (i.e. it still includes int64 updatedRelayerFeePct instead of uint256 updatedOutputAmount) which means that the depositor 
signature will never match the passed in "speed up params".
This PR also adds unit tests for both `depositUSS` and `speedUpUSSDeposit`.

fix(SpokePool): Address speedup USS depositor signature logic and add unit tests

---

contracts/Polygon_SpokePool.sol
contracts/SpokePool.sol

Originally I used block.timestamp in new USS functions in order to avoid a potential JUMP opcode when calling `getCurrentTime()` however @pxrl astutely pointed out that downstream tests like those in `relayer-v2` manipulate time via `MockSpokePool.setCurrentTime()` in unit tests so using `block.timestamp` might make it harder for these unit tests to pass when modified to address the USS functions

improve(SpokePool): Replace block.timestamp with getCurrentTIme()

---

contracts/SpokePool.sol
contracts/interfaces/USSSpokePoolInterface.sol
contracts/test/MockSpokePool.sol
test/MerkleLib.Proofs.ts
test/SpokePool.Deposit.ts
test/SpokePool.Relay.ts
test/SpokePool.SlowRelay.ts
test/chain-specific-spokepools/Polygon_SpokePool.ts
test/fixtures/SpokePool.Fixture.ts

1. Reduce the number of params passed into fillUSS-related functions by 1 by removing `destinationChainId` from the passed in `struct`. This also has the added safety benefit of not allowing the caller to set the `destinationChainId` and instead forces them to reference a relay hash using the SpokePool's `chainId()`.
2. This additionally saves gas in these functions because it no longer needs to check the input `relayData.destinationChainId` against the contract's `chainId`.
Changes implementation of how we construct relay hashes for USS fills by now hashing all of the `USSRelayData` params as a struct (i.e. as a DepositData struct) WITH the `chainId()` so that the destinationChainId is still hashed to protect against replay attacks

improve(SpokePool): Remove `destinationChainId` from USSRelayData struct

---

contracts/SpokePool.sol
contracts/test/MockSpokePool.sol
test/SpokePool.ExecuteRootBundle.ts

Also refactors the SpokePool.sol code so that the validation of merkle leaf properties are done as close to their usage within the logic as possible

feat: Add _distributeRelayerRefund unit tests

---

hardhat.config.ts
tasks/rescueStuckScrollTxn.ts

How we can replay failed L1 -> L2 messages. 
**NOTE:** per the Scroll docs, we **cannot** replay L2 -> L1 transactions. All tokens are burned.
L1 -> L2 test transactions:
1. Initial bridge request that fails: 
https://sepolia.etherscan.io/tx/0x7e74b85bdaca0358021f886fb4fbab3a72660843add5201e484285bde5ba9f04
2. Visible failed transaction: https://sepolia.scrollscan.com/tx/0x1e384bb0fb42c67234163384ce21ff836e7031210642f4f3764874eb526fc89b
3. Replay Transaction from calling this task: https://sepolia.etherscan.io/tx/0x0042f7b4792d8c08249db10c49748f29cbdd408205d3932812b44e39aa9f4e58
4. Successful landing of funds: https://sepolia.scrollscan.com/tx/0x6cd5273c7a9b16a41eab1c6319a0f36ebf7ea8b8a81ab4be5c5c45179bb130ff
The rescue script was run with the following parameters:
```
yarn hardhat …
```

feat(Scroll): add rescue script for stuck txns

---

contracts/interfaces/V3SpokePoolInterface.sol

This was renamed in all other events and function prototypes, but it appears to have been missed here. Having it named `relayer` rather than `exclusiveRelayer` creates friction when unpacking the event in the sdk.

refactor: Rename V3FundsDeposited relayer -> exclusiveRelayer

---

contracts/SpokePool.sol
test/SpokePool.ExecuteRootBundle.ts

We removed these event parameters because they were unused but didn't realize this would inadvertently break clients that query these event signatures. Once contracts are updated, clients wouldn't be able to query historical instances of these events, which is required for the `finalizer` to to finalize remaining withdrawals from deprecated contract versions.

improve: Restore TokensBridged and ExecutedRelayerRefundLeaf event signatures

---

contracts/SpokePool.sol

This makes unit tests easier in `relayer-v2` to simulate running against a contract that has emitted both `FundsDeposited` and `V3FundsDeposited` events.

feat: Add FundsDeposited event for backwards compatible ABI creation

---

contracts/SpokePool.sol
contracts/interfaces/V3SpokePoolInterface.sol
test/SpokePool.SlowRelay.ts

Don't permit a slow fill request to be issued when the deposit in                                                                                                                                                                                              
question is still within the specified exclusivity deadline. This                                                                                                                                                                                              
protects deposits where a relayer has made a commitment to fill within                                                                                                                                                                                         
a specified deadline, so they …

improve: L01 Fillers Might Lose Their Collateral

---

contracts/Arbitrum_SpokePool.sol
contracts/Linea_SpokePool.sol
contracts/Ovm_SpokePool.sol
contracts/PolygonZkEVM_SpokePool.sol
contracts/Polygon_SpokePool.sol
contracts/Scroll_SpokePool.sol
contracts/ZkSync_SpokePool.sol

These chain-specific bridge events contained some subtle errors, but add                                                                                                                                                                                       
no marginal value over the TokensBridged event emitted in the parent                                                                                                                                                                                           
contract. Remove them because they're not currently used by any known                                                                                                                                                                                          
event consumers and have no …

improve: L06 Inconsistent And Misleading Events Emitted When Bridging To HubPool

---

contracts/SpokePool.sol
contracts/interfaces/V3SpokePoolInterface.sol
test/SpokePool.ExecuteRootBundle.ts

chainId is not useful because it is known based on the SpokePool being queried. Also, the marginal value of indexing the leafId on top of the rootBundleId is pretty minimal, so instead index l2TokenAddress and fillsRefundedRoot.

improve(SpokePool): Delete chainId in ExecutedV3RelayerRefundRoot event

---

contracts/test/MockSpokePool.sol
package.json
test/fixtures/SpokePool.Fixture.ts

Currently,  sdk-v2 and relayer-v2 use this repo's test-util.ts export for their unit tests, which tests against this repo's MockSpokePool. Some of these functions will fail because the existing 
MockSpokePool doesn't have any way to emit FundsDeposited events, which these functions query for.

feat: Update MockSpokePool to include a depositV2 test function

---

contracts/test/MockSpokePool.sol
package.json
test/fixtures/HubPool.Fixture.ts
test/fixtures/SpokePool.Fixture.ts

sdk-v2, relayer-v2 might want to override this functionality. For example, sdk-v2 doesn't need all the require statements and doesn't actually need to pull tokens from the caller

improve: Make MockSpokePool.depositV2 virtual

---

contracts/SpokePool.sol

Add explicit handling for non-expiring v3 deposits that are made via the backwards-compatible deposit() function.
Authored by Nick.

feat: M01 Deadline Buffer for Fills Is Not Always Respected

---

contracts/interfaces/SpokePoolInterface.sol

This will no longer be deprecated now that V3RelayerRefundLeaf has been removed.

fix: Remove RelayerRefundLeaf deprecation notice

---

package.json

npm already had 2.5.0-beta.6 and 2.5.0-beta6.1. Have resolved why they were there, so bump to 2.5.0-beta.7.

chore: Bump beta again

---

deployments/base-sepolia/Base_SpokePool.json
deployments/sepolia/Ethereum_SpokePool.json

These were introduced as a result of a bad merge. They're testnet deployments only; the production deployments were merged separately by Nick.

fix: Remove duplicate events from Sepolia ABIs

---

utils/index.ts

This PR will remove hardhat from the standard import path. This means that ts/js code that does:
```
import ... from "@across-protocol/contracts-v2"
```
will not need a hardhat config and will not spin up a local hardhat node by default. I've verified that the files in utils don't seem to be used in sdk-v2 or relayer-v2.
I think this was accidentally moved into our production exports in a larger change: https://github.com/across-protocol/contracts-v2/pull/272.

fix: remove hardhat from standard import

---

deploy/029_deploy_linea_spokepool.ts

The goal of this PR is to deploy Linea's ChainAdapter & SpokePool to the Eth/Linea mainnets respectively. The commands that will be run are:
_Deploy ChainAdapter_
```
yarn hardhat deploy --network mainnet --tags LineaAdapter 
```
_Deploy SpokePool_
```
yarn hardhat deploy --network linea --tags LineaSpokePool
```

feat(linea): pre-deploy of linea

---

contracts/SpokePool.sol
package.json

This PR aims at returning the V2 events for FilledRelay, FundsDeposited, and RequestedSpeedUpDeposit. After an internal discussion with @nicholaspai and @pxrl this feels like the lowest lift to push the deployments forward without having to make large changes to the SDK.

chore(V2): revert events

---

contracts/test/MerkleLibTest.sol
contracts/test/MockSpokePool.sol
contracts/test/V2MerkleLib.sol
contracts/test/interfaces/MockV2SpokePoolInterface.sol
package.json
test/MerkleLib.utils.ts
test/fixtures/SpokePool.Fixture.ts

The relayer repository requires these functions to be available for use in test, effectively as a protection against regressions. In the long run this will be a pain to retain, but for now it's necessary to permit onchain v2 functions to be removed.

chore: Restore v2 functions for relayer test

---

contracts/Linea_SpokePool.sol

msg.value is unconditionally wrapped by _preExecuteLeafHook(), so it must be unwrapped again before sending ETH back to the HubPool.

fix(Linea): Unwrap correct amount before returning ETH to HubPool

---

contracts/SwapAndBridge.sol

We need to increase the allowance of the `_swapToken` instead of `_acrossInputToken` before executing the swap.
Example success tx https://polygonscan.com/tx/0xbde4fe5e4844294e85b0f5e17af75e409deb6a006f508abf9e7127df5a4cf389

fix(SwapAndBridge): increase allowance of correct token

---

contracts/SwapAndBridge.sol
storage-layouts/Arbitrum_SpokePool.json
storage-layouts/Base_SpokePool.json
storage-layouts/Ethereum_SpokePool.json
storage-layouts/Linea_SpokePool.json
storage-layouts/Optimism_SpokePool.json
storage-layouts/Polygon_SpokePool.json
storage-layouts/ZkSync_SpokePool.json

This will be important to track for frontends to determine when a non-supported token is swapped into a supported token via this contract before submitting an Across Bridge

feat: Add event in SwapAndBridge

---

contracts/SpokePool.sol
storage-layouts/Arbitrum_SpokePool.json
storage-layouts/Base_SpokePool.json
storage-layouts/Ethereum_SpokePool.json
storage-layouts/Linea_SpokePool.json
storage-layouts/Mode_SpokePool.json
storage-layouts/Optimism_SpokePool.json
storage-layouts/Polygon_SpokePool.json
storage-layouts/ZkSync_SpokePool.json
test/SpokePool.Deposit.ts

We want to support a user flow where a depositor can be paired off-chain with an `exclusiveRelayer` and give them a very short exclusivity window (think ~2-4 seconds) but we don't want the depositor to have to consider the latency between their deposit txn being submitted to the mempool and when it is mined. Instead, good depositor UX essentially requires that an offset can be specified so that a depositor can specify the amout of exclusivity the filler can get after a deposit is mined.

feat(SpokePool): Add depositExclusive() function to support exclusive order routing

---

scripts/checkStorageLayout.sh
storage-layouts/Arbitrum_SpokePool.json
storage-layouts/Base_SpokePool.json
storage-layouts/Ethereum_SpokePool.json
storage-layouts/Linea_SpokePool.json
storage-layouts/Mode_SpokePool.json
storage-layouts/Optimism_SpokePool.json
storage-layouts/Polygon_SpokePool.json
storage-layouts/ZkSync_SpokePool.json

Remove props like astID and anything in types that are not minimally neccessary to compare storage layouts.
Namely, we care about which slots state variables are using, which are ultimately downstream of `types` and independent of the AST layout

improve(forge-ci): Ignore astId and other non-storage slot related props when diffing storage layouts

---

contracts/erc7683/ERC7683Across.sol

- should use abi.encode instead of abi.encodePacked when encoding data into a hash
- Should keccak256 any `bytes` member like `message` in the `AcrossOrderData` struct

fix(ERC7683Permit2Lib): Comply with EIP712

---

contracts/Blast_SpokePool.sol
contracts/Optimism_SpokePool.sol
contracts/Ovm_SpokePool.sol
contracts/test/MockBedrockStandardBridge.sol
scripts/checkStorageLayout.sh
storage-layouts/Base_SpokePool.json
storage-layouts/Blast_SpokePool.json
storage-layouts/Mode_SpokePool.json
storage-layouts/Optimism_SpokePool.json
test/chain-specific-spokepools/Optimism_SpokePool.ts

bridgeERC20To can be used to bridge native L2 tokens (without L1 counterparts and specifically does not contain a `l1Token()` function in the L2 erc20 contract) if an L1 remote token is identified.
This call require the spoke pool to set an allowance on the standard bridge before calling `bridgeERC20To`

improve(OVM_SpokePool): Use bridgeERC20To to bridge native L2 tokens if admin decides to support them

---

contracts/Blast_SpokePool.sol
contracts/erc7683/ERC7683Across.sol

Throughout the codebase, there are several instances of variables having different names than those in the original interface defining them:
- The mode variable from the IERC20Rebasing has a different name than the corresponding variable declared in the [configure](https://blastscan.io/address/0x4ef0d788470e2feb6559b93075ec5be51dba737d#code#F4#L220) function of the USDB implementation contract deployed on the Blast blockchain.
- The recipient variable from the IBlast interface has a different name than the [corresponding variable](https://blastscan.io/address/0xc0d3c0d3c0d3c0d3c0d3c0d3c0d3c0d3c3d30002#code#F1#L49) declared in the Blast implementation contract deployed on the Blast blockchain.
- The settlerContract variable used for the calculation of CROSS_CHAIN_ORDER_TYPE has a different …

improve: Align interface variable names

---

contracts/chain-adapters/Blast_Adapter.sol
contracts/chain-adapters/Mode_Adapter.sol
contracts/libraries/CircleCCTPAdapter.sol

Avoid any accidental enabling of CCTP for chains like Blast and Mode which are not enabled by Circle

improve: Use dummy CircleCCTPAdapter domain ID for chains not supported by CCTP

---

contracts/handlers/MulticallHandler.sol

> Within `MulticallHandler.sol `, several events do not have indexed parameters:
> - The CallsFailed event
> - The DrainedTokens event
> To improve the ability of off-chain services to search and filter for specific events, we should index the event parameters.

fix(MulticallHandler): add indexed event parameters

---

contracts/handlers/MulticallHandler.sol
test/foundry/local/MulticallHandler.t.sol

> The `attemptCalls` function of the `MulticallHandler` contract enables users to specify and execute custom operations on a target blockchain right after tokens are bridged. It performs these operations by doing a series of low-level calls to the target addresses with the given data. If any of these calls fails, the entire chain of transactions is reverted in order to
protect users from losing their assets.
> In Solidity, whenever high-level calls are made to an address without any code, the execution reverts. However, when low-level calls are made to an empty address, they are considered successful. It means that if a user mistakenly specifies an address not containing any code as a target, their transaction will succeed, whereas it would have failed if high-level calls had been made. …

fix(MulticallHandler): revert transaction when calling an EOA with calldata

---

contracts/Lisk_SpokePool.sol
contracts/chain-adapters/Lisk_Adapter.sol
deploy/042_deploy_lisk_adapter.ts
deploy/043_deploy_lisk_spokepool.ts
deploy/consts.ts

This commit adds the Lisk Adapter/Spoke pool contracts as well as their deployment scripts. Since Lisk is a standard OP stack chain, both contracts are clones of the corresponding Base/Mode contracts. Once merged, a following PR will be added to deploy the contracts to mainnet.

feat: add Lisk adapter/spoke pool

---

package.json
yarn.lock

Needed to make the repository aware of Lisk.

chore: bump @across-protocol/constants version

---

contracts/Blast_SpokePool.sol

USDB L2 -> L1 transfers are failing due to an incorrect function signature where the gas type was assumed to be uint256, as it is on other OP Stack chains, rather than uint32, which is what it is on Blast.

fix: fix usdb l2 bridge signature

---

utils/utils.hre.ts

This is the follow up to [this question](https://github.com/across-protocol/contracts/pull/549#discussion_r1664450124) in the Blast deployments PR.

feat(utils): make unsafeAllow parameters configurable

---

contracts/Blast_SpokePool.sol

This commit upgrades the `Blast_SpokePool` so that it is compatible with the `Blast_DaiRetriever` contract on mainnet. It just adds a new immutable variable `BLAST_RETRIEVER` which is the new recipient of cross-chain spoke pool rebalances.

feat(Blast): send tokens to blast retriever

---

deployments/deployments.json

The SpokePoolVerifier deployments listed are pre-audit and are not yet used in production, so revert to the variant currently used.

fix: Revert to production SpokePoolVerifier deployments

---

deploy/003_deploy_optimism_spokepool.ts
deploy/005_deploy_arbitrum_spokepool.ts
deploy/007_deploy_ethereum_spokepool.ts
deploy/011_deploy_polygon_spokepool.ts
deploy/016_deploy_zksync_spokepool.ts
deploy/025_deploy_base_spokepool.ts
deploy/029_deploy_linea_spokepool.ts
deploy/036_deploy_blast_spokepool.ts
deploy/039_deploy_mode_spokepool.ts
deploy/043_deploy_lisk_spokepool.ts
deploy/047_deploy_redstone_spokepool.ts
deploy/049_deploy_zora_spokepool.ts
deployments/deployments.json
src/DeploymentUtils.ts
utils/utils.hre.ts

The majority of SpokePool deployment scripts have been updated to support deploying only implementation contracts. This is done with the knowledge that there are already pre-existing deployments on these chains, but it introduces a risk that using one of these scripts as the template for a new chain will inadvertently result in skipping deployment of the proxy contact. Instead, whether to deploy a new proxy or not can be inferred by whether the contract exists in deployments.json.

improve(deploy): Improve SpokePool deployment UX

---

contracts/chain-adapters/Arbitrum_Adapter.sol
contracts/chain-adapters/Arbitrum_CustomGasToken_Adapter.sol
contracts/chain-adapters/Arbitrum_CustomGasToken_Funder.sol

- Example `createRetryableTicket` paying for submission with custom gas token and also sending custom gas token to L2: https://etherscan.io/tx/0xfbcd1f29a0db9971c885815e74499f3a545e7c0ee0a2d06ee4a94dc08c03f4e0
- Example `outboundTransfer` paying with custom gas token and sending a different ERC20 to L2: https://etherscan.io/tx/0x7f65fff856520cc419c3a9f43a61f3427ad495ddf5dc81276c2767ac74242e39

feat(Arbitrum_Adapter): Support custom gas token

---

contracts/SpokePool.sol
test/SpokePool.Deposit.ts
test/SpokePool.Relay.ts

Better depositor UX if they can specify an offset that is relative to the time that their deposit mines, so they do not have to account for any off-chain latency

feat(SpokePool): Specify exclusivityDeadlineOffset by default

---

contracts/chain-adapters/DonationBox.sol

Makes it more clear that anyone depositing tokens to the box is willingly giving them away to the owner. The contract is mostly designed to be used by the owner to deposit fundsto. be used  for future transactions.

improve: Rename Arbitrum_CustomGasToken_Funder to DonationBox

---

contracts/SpokePool.sol

This call is already loaded into memory above within the same function

improve(SpokePool): Remove redundant getCurrentTime() call

---

contracts/SpokePool.sol

In most cases, we can avoid having to do the `extcodesize` call that’s inside `isContract()`.
This could save [~2600](https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a5-balance-extcodesize-extcodehash) gas per call for non ETH bridges to EOAs

improve(SpokePool): deposit with message gas optimization

---

programs/svm-spoke/src/instructions/admin.rs
programs/svm-spoke/src/instructions/deposit.rs
programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/instructions/handle_receive_message.rs
programs/svm-spoke/src/instructions/slow_fill.rs
test/svm/SvmSpoke.Deposit.ts
test/svm/SvmSpoke.Fill.ts
test/svm/SvmSpoke.HandleReceiveMessage.ts
test/svm/SvmSpoke.Routes.ts
test/svm/SvmSpoke.SlowFill.ts

Adds missing account constraints in `svm-spoke` program. This also makes sure all relevant function parameters are validated to be consistent with context accounts.

fix(svm): add missing constraints in svm spoke pool

---

programs/svm-spoke/src/instructions/slow_fill.rs
test/svm/SvmSpoke.SlowFill.ts

Adds overriding to local `chain_id` in `execute_v3_slow_relay_leaf`. This makes SVM behavior consistent with EVM SpokePool: if someone was trying to replay slow fill targeted at another chain, this should fail the proof verification due to mismatched chain id.

fix(svm): override chain id in executing slow fill

---

package.json
programs/svm-spoke/src/event.rs
programs/svm-spoke/src/instructions/admin.rs
programs/svm-spoke/src/instructions/bundle.rs
programs/svm-spoke/src/instructions/deposit.rs
programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/instructions/slow_fill.rs
programs/svm-spoke/src/lib.rs
programs/svm-spoke/src/state/mod.rs
programs/svm-spoke/src/state/state.rs
test/svm/SvmSpoke.Bundle.ts
test/svm/SvmSpoke.Deposit.ts
test/svm/SvmSpoke.Fill.ts
test/svm/SvmSpoke.Ownership.ts
test/svm/SvmSpoke.Routes.ts
test/svm/SvmSpoke.SlowFill.ts
test/svm/SvmSpoke.TokenBridge.ts
test/svm/utils.ts

PR add an additional events and pulls events into a common defined location.

Add missing events and re-factor event location

---

programs/svm-spoke/src/instructions/admin.rs
programs/svm-spoke/src/instructions/deposit.rs
test/svm/SvmSpoke.Deposit.ts
test/svm/SvmSpoke.HandleReceiveMessage.ts
test/svm/SvmSpoke.Routes.ts
test/svm/SvmSpoke.common.ts

- Fix routes seed to use state key to prevent passing fake enabled routes

feat(svm-routes): add additional param to block non-enabled routes

---

programs/svm-spoke/src/instructions/bundle.rs
src/SvmUtils.ts
test/svm/SvmSpoke.Bundle.ts

Increases max refund count by using Address Lookup Table (ALT). This is capped at 19 refunds as higher count causes out of memory panic when looping through refund transfers. To overcome this limit we would need to split individual refund claims in separate transaction. And if we split this, then we don't really need to use ALT.
Edit: limit is now increased to 21 by dropping expensive debug msg of input data. Now the bottleneck is calldata size, but that could be resolved by passing it from a buffer account.

test: use address lookup table in max refund test

---

programs/svm-spoke/src/instructions/bundle.rs
test/svm/SvmSpoke.Bundle.ts

Anchor would shrink root_bundle account when executing leaves in reverse order. This fixes the issue by adding current account size as minimum condition in realloc constraint.

fix: do not shrink root bundle account

---

programs/test/src/lib.rs
test/svm/Utils.Events.ts

- Add tests play with log truncation and ways to recover the truncated data.

test(svm-events): large log truncation

---

contracts/chain-adapters/Arbitrum_Forwarder.sol
contracts/chain-adapters/Ovm_Forwarder.sol
test/evm/foundry/local/Forwarder.t.sol

In the forwarder PR here https://github.com/across-protocol/contracts/pull/609/files I added a function to be called upon initialization but did not add the actual entrypoint function. This PR adds these functions to the chain-specific forwarders.

fix: add init functions to forwarders

---

contracts/chain-adapters/DonationBox.sol
contracts/chain-adapters/ZkStack_Adapter.sol
contracts/chain-adapters/ZkStack_CustomGasToken_Adapter.sol

This PR adds two adapters: one for ZkStack with custom gas tokens and one for ZkStack with ETH gas tokens. Note: we were previously told that our existing adapter would work for ZkStack chains that used ETH, but after reading the code, I found restrictions on using legacy methods for any chain that isn't ZkSync.

feat: ZkStack Adapters

---

tasks/enableL1TokenAcrossEcosystem.ts

This change updates the `enable-l1-token-across-ecosystem` task to do the following:
- Auto-inherit the complete set of known chain IDs if not otherwise specified via the --chains option.
- Display token symbols alongside token addresses.
- Drop superfluous numbers from log messages (they were manually maintained and non-sequential).
- Throw on default network (hardhat).
- Sub in symbolic chainId names instead of hardcoded values.
- Sort chain IDs numerically for cleaner display when iterating over chains.
- Append setPoolRebalanceRoute calldata.

improve(tasks): Update deposit route script

---

contracts/SpokePool.sol
contracts/erc7683/ERC7683.sol
contracts/erc7683/ERC7683Across.sol
contracts/erc7683/ERC7683OrderDepositor.sol
contracts/erc7683/ERC7683OrderDepositorExternal.sol
contracts/interfaces/V3SpokePoolInterface.sol

This PR implements the updated version of ERC-7683 as described [here](https://github.com/across-protocol/ERCs/pull/1). This change ended up being more involved than expected.
There are only a few open questions remaining:
1. Should this handle pre-fills? Right now, it assumes the incrementing deposit id. Would require #583 to be merged first to support them.
2. Quote timestamp is assumed to be the deposit timestamp for Onchain deposits. I think this is probably a reasonable initial assumption to keep the AcrossOrderData struct consistent between the onchain and gasless versions, but we could add a param for it if necessary.
3. The external depositor contract (which we rely on since we don't have room to merge the bulk of this into the spoke) now needs a lookup table of destination …

feat: add updated implementation of ERC-7683

---

tsconfig.json

typeRoots should have been placed under compilerOptions in tsconfig.json

fix: type roots config

---

package.json
programs/svm-spoke/Cargo.toml
programs/svm-spoke/src/instructions/admin.rs
programs/svm-spoke/src/instructions/deposit.rs
programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/instructions/slow_fill.rs
programs/svm-spoke/src/instructions/testable.rs
programs/svm-spoke/src/lib.rs
programs/svm-spoke/src/state/state.rs
programs/test/Cargo.toml
scripts/svm/initialize.ts
test/svm/SvmSpoke.Ownership.ts
test/svm/SvmSpoke.common.ts

Simplifies the code by handling current time using cargo features. Only when built with test feature enabled, the implementation stores and gets time via state account. In production build actual current time is fetched.

fix(svm): use cargo feature to set time in tests

---

programs/svm-spoke/src/error.rs
programs/svm-spoke/src/instructions/bundle.rs
programs/svm-spoke/src/instructions/deposit.rs
programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/instructions/slow_fill.rs
programs/svm-spoke/src/instructions/token_bridge.rs
programs/svm-spoke/src/utils/cctp_utils.rs
programs/svm-spoke/src/utils/merkle_proof_utils.rs
programs/test/src/lib.rs
test/svm/SvmSpoke.SlowFill.ts

Improves SVM SpokePool to be more consistent with EVM implementation. This replaces require statements with if/revert pattern used in EVM, and fixes the reverse logic error in slow fill deadline checks.

fix(svm): make svm spoke pool logic more consistent with evm

---

programs/svm-spoke/src/error.rs
programs/svm-spoke/src/instructions/bundle.rs
test/svm/SvmSpoke.Bundle.ts

SVM implementation of SpokePool lacked the check on the matching length for refund account and amount arrays when executing relayer refund leaf.

fix(svm): check invalid refund leaf

---

programs/svm-spoke/src/instructions/fill.rs
test/svm/SvmSpoke.Fill.ts

EVM logic skips the fill transfer if relayer is the same as recipient. This adds the same logic in SVM SpokePool.
Fixes: https://linear.app/uma/issue/ACX-2929/instructionsfillrs-check-what-happens-if-the-relayer-and-recipient-are

fix(svm): no transfer on self-relay

---

programs/svm-spoke/src/instructions/admin.rs
programs/svm-spoke/src/instructions/handle_receive_message.rs
programs/svm-spoke/src/lib.rs
scripts/svm/enableRoute.ts
test/svm/SvmSpoke.Deposit.ts
test/svm/SvmSpoke.Routes.ts

It is easier to use Pubkey as origin_token parameter in set_enable_route.
Fixes: https://linear.app/uma/issue/ACX-2917/instructionsadminrs-is-it-possible-to-replace-origin-token-with-pubkey

fix(svm): use pubkey in origin token

---

programs/svm-spoke/src/event.rs
programs/svm-spoke/src/instructions/admin.rs
programs/svm-spoke/src/state/state.rs
test/svm/SvmSpoke.Bundle.ts
test/svm/SvmSpoke.RefundClaims.ts
test/svm/SvmSpoke.SlowFill.ts
test/svm/SvmSpoke.TokenBridge.ts

Proposed changes in this PR:
- Add relay root bundle event

feat(svm): relay root bundle event

---

programs/svm-spoke/src/event.rs
programs/svm-spoke/src/instructions/admin.rs
programs/svm-spoke/src/lib.rs
test/svm/SvmSpoke.Bundle.ts

- Add emergency_delete_root_bundle

feat(svm): add emergency delete bundle

---

programs/svm-spoke/src/error.rs
programs/svm-spoke/src/instructions/refund_claims.rs
programs/svm-spoke/src/lib.rs
test/svm/SvmSpoke.RefundClaims.ts

Though claim accounts are being closed automatically when claiming the refund, there might be a scenario where relayer refunds were executed with ATA after initializing the claim account. In such cases, the initializer should be able to close the claim account manually.
Fixes: https://linear.app/uma/issue/ACX-3024/instructionsrefund-claimsrs-add-manual-instruction-to-close-claim

fix(svm): close claim account manually

---

programs/svm-spoke/src/instructions/admin.rs
programs/svm-spoke/src/instructions/bundle.rs
programs/svm-spoke/src/instructions/deposit.rs
programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/instructions/handle_receive_message.rs
programs/svm-spoke/src/instructions/instruction_params.rs
programs/svm-spoke/src/instructions/refund_claims.rs
programs/svm-spoke/src/instructions/slow_fill.rs
programs/svm-spoke/src/instructions/testable.rs
programs/svm-spoke/src/instructions/token_bridge.rs
scripts/svm/remotePauseDeposits.ts
test/svm/SvmSpoke.HandleReceiveMessage.ts

Removes redundant mutables. This also allows changing the signer PDA in self-invoked remote CCTP calls to readonly.
Fixes: https://linear.app/uma/issue/ACX-2918/instructionsadminrs-check-if-state-needs-to-be-mut-here-and-in-other

fix(svm): remove redundant mutables

---

test/evm/hardhat/SpokePool.ExecuteRootBundle.ts
test/svm/SvmSpoke.Bundle.ts
test/svm/utils.ts

- Add tests in hardhat to verify that a tree with mixed leaves (sorted by chain and mixed together) using different hashing functions is fully verifiable on the EVM.
- Add equivalent tests for the SVM.

test: multi-chain verifiable merkle tree

---

programs/svm-spoke/src/error.rs
programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/instructions/slow_fill.rs
scripts/svm/simpleFill.ts
test/svm/SvmSpoke.Fill.ts
test/svm/SvmSpoke.SlowFill.ts

This removes redundant accounts from fill and slow fill instructions.
Fixes: https://linear.app/uma/issue/ACX-3020/instructionsfillrs-recipient-systemaccount-might-be-redundant
Fixes: https://linear.app/uma/issue/ACX-3019/instructionsfillrs-should-relayer-be-the-same-as-signer

fix(svm): remove redundant accounts

---

programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/instructions/slow_fill.rs
programs/svm-spoke/src/lib.rs
scripts/svm/simpleFill.ts
test/svm/SvmSpoke.Fill.ts
test/svm/SvmSpoke.SlowFill.ts

feat: move drift from svm-dev back into master

---

programs/svm-spoke/src/instructions/bundle.rs
test/svm/utils.ts

- relayer refund leaf ordering to match [evm's one](https://github.com/across-protocol/contracts/blob/f5e48d9321bb239047ad22178b89d725ec9efb8b/contracts/interfaces/SpokePoolInterface.sol#L9)

refactor(svm): relayer refund leaf order

---

programs/svm-spoke/src/error.rs
programs/svm-spoke/src/instructions/admin.rs
programs/svm-spoke/src/instructions/handle_receive_message.rs
programs/svm-spoke/src/utils/cctp_utils.rs
scripts/svm/simpleFakeRelayerRepayment.ts
test/svm/SvmSpoke.Bundle.ts
test/svm/SvmSpoke.HandleReceiveMessage.ts
test/svm/SvmSpoke.RefundClaims.ts
test/svm/SvmSpoke.SlowFill.ts
test/svm/SvmSpoke.TokenBridge.ts

We require ability to relay and emergency delete root bundles over CCTP.
Fixes: https://linear.app/uma/issue/ACX-3029/instructionsadminrs-remote-relay-emergency-delete-root-bundle

fix(svm): root bundles over cctp

---

programs/svm-spoke/src/instructions/handle_receive_message.rs

- Add comment to explain the `setEnableRoute` function signature translation

docs(svm): comment to explain setEnableRoute conversion

---

programs/svm-spoke/src/instructions/deposit.rs
programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/instructions/slow_fill.rs
test/svm/SvmSpoke.Fill.ts

We were unnecessarily restricting relayer token account in the fill instruction to be canonically derived from the relayer and mint addresses. By replacing associated_token constraints with token constraints this would allow the relayer to pass any token account as long as its mint and authority matches.
Overall, we want to use canonical token accounts for vault and fill/slow fill recipients (hence, associated_token constraints) and any valid token accounts for all others.
Also, some of mint accounts were incorrectly using token constraints for their program account checks. Event the checks are implemented the same way (account being owned by the token program), Anchor error message is slightly different.
Fixes: https://linear.app/uma/issue/ACX-2925/instructionsfillrs-consistent-token-impo …

fix(svm): consistent anchor token constraints

---

hardhat.config.ts
package.json
tasks/testChainAdapter.ts
yarn.lock

This has some limitations around USDC native/bridged coincidence, but should otherwise be useful for testing chain adapters for new deployments (where CCTP is very unlikely to be enabled anyway).

feat: hardhat task to test chain adapter token bridging

---

contracts/SpokePool.sol
contracts/interfaces/V3SpokePoolInterface.sol
test/evm/hardhat/SpokePool.Relay.ts
test/evm/hardhat/SpokePool.SlowRelay.ts

The new relative exclusivity check has not been propagated to fillV3RelayWithUpdatedDeposit() or requestV3SlowFill(). Identified via test case failures in the relayer.
This is a very-low criticality issue. It's very unlikely that any relayer would be trying to call `fillV3RelayWithUpdatedDeposit()` within the exclusivity window. There's a slightly higher chance of hitting this issue on slow fill requests because the RL relayer is fast enough to hit the probable exclusivity windows on some routes for larger transfers, which is where a token shortfall is more likely.

fix(SpokePool): Enforce exclusivity consistently

---

programs/svm-spoke/src/error.rs
programs/svm-spoke/src/instructions/create_token_accounts.rs
programs/svm-spoke/src/instructions/mod.rs
programs/svm-spoke/src/lib.rs
test/svm/SvmSpoke.CreateTokenAccounts.ts
test/svm/SvmSpoke.Fill.ts

Adds method to create multiple associated token accounts. This instruction can be prepended to other instructions that expect ATAs being initialized.

fix(svm): instruction to create multiple token accounts

---

.rustfmt.toml
package.json
programs/svm-spoke/src/constraints.rs
programs/svm-spoke/src/instructions/admin.rs
programs/svm-spoke/src/instructions/bundle.rs
programs/svm-spoke/src/instructions/create_token_accounts.rs
programs/svm-spoke/src/instructions/deposit.rs
programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/instructions/handle_receive_message.rs
programs/svm-spoke/src/instructions/instruction_params.rs
programs/svm-spoke/src/instructions/mod.rs
programs/svm-spoke/src/instructions/refund_claims.rs
programs/svm-spoke/src/instructions/slow_fill.rs
programs/svm-spoke/src/instructions/token_bridge.rs
programs/svm-spoke/src/lib.rs
programs/svm-spoke/src/state/refund_account.rs
programs/svm-spoke/src/state/state.rs
programs/svm-spoke/src/utils/cctp_utils.rs
programs/svm-spoke/src/utils/merkle_proof_utils.rs
programs/test/src/lib.rs
scripts/preCommitHook.sh

We introduced prettier plugin to lint rust code, mostly to format Anchor attribute macros that rustfmt does not handle well. This though, brought in quite a lot of opinionated formatting for the rest of the rust code from prettier. In order to be more aligned with default rust formatting, this PR introduces wrapper pre-commit hook that first runs prettier-quick and then applies rustfmt on top for any staged rust files.
The only deviation from default rust formatting this PR adds is extending maximum line with to 120 characters to be consistent with other parts of this repo.

fix: rust linting

---

test/svm/SvmSpoke.Fill.ts

feat: show that we can create ATA in same transaction as fill

---

programs/svm-spoke/src/instructions/handle_receive_message.rs
programs/svm-spoke/src/lib.rs

For the sake of consistency use free function in internal handle_receive_message call. This also simplifies the external function.
Fixes: https://linear.app/uma/issue/ACX-3102/librs-refactor-handle-receive-message-to-be-consistent-with-using-free

fix(svm): use free function in handling cctp

---

contracts/erc7683/ERC7683.sol
contracts/erc7683/ERC7683Across.sol
contracts/erc7683/ERC7683OrderDepositor.sol

Standard will likely be updated with changes [here](https://github.com/ethereum/ERCs/pull/689/files) so this PR adjusts for those changes:
- `originChainId` of intent is now uint256
- `orderId` is a new parameter in the `ResolvedCrossChainOrder` struct, which in Across' system can be the hash of the `V3RelayData`

improve(ERC7683): Adjust for updated ERC specs

---

.github/workflows/publish.yml
package.json

Some packages are no longer compatible with the node version we were using: https://github.com/across-protocol/contracts/actions/runs/11746427003

fix: update node version for publish action

---

Anchor.toml

CCTP upgraded their messanger program on devnet that broke our forking tests. This switches to mainnet forking that still has the original CCTP instance.

fix(svm): fork cctp from mainnet

---

contracts/erc7683/ERC7683OrderDepositorExternal.sol

> The ERC7683OrderDepositorExternal contract contains the setDestinationSettler [function](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/erc7683/ERC7683OrderDepositorExternal.sol#L38-L42) which provides a mapping of chain ID to that chain's settler contract address. This value is accessed through the [_destinationSettler](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/erc7683/ERC7683OrderDepositorExternal.sol#L80-L82) function of the same contract and is used by the inherited ERC7683OrderDepositor contract when constructing the [fill instructions](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/erc7683/ERC7683OrderDepositor.sol#L2 …

fix: C-01 Missing Access Control for `setDestinationSettler`

---

contracts/chain-adapters/ZkStack_Adapter.sol
contracts/chain-adapters/ZkStack_CustomGasToken_Adapter.sol
test/evm/foundry/local/ZkStack_Adapter.t.sol

> The relayTokens [function](https://github.com/across-protocol/contracts/blob/5a0c67c984d19a3bb843a4cec9bb081734583dd1/contracts/chain-adapters/ZkStack_Adapter.sol#L109-L122) of the ZkStack_Adapter is intended to facilitate transfers from the HubPool on the Ethereum Mainnet to ZkStack chains, having ETH as the gas token, via the BridgeHub. The relayTokens [function](https://github.com/across-protocol/contracts/blob/5a0c67c984d19a3bb843a4cec9bb081734583dd1/contracts/chain-adapters/ZkStack_CustomGasToken_Adapter.sol#L141) of the ZkStack_CustomGasToken_Adapter contract enables this functionality for chains with a custom gas token.
> For ZkStack_Adapter, when transferring WETH, the relayTokens function [unwraps](https://github.com/across-protocol/contracts/blob/5a0c67c984d19a3bb843a4cec9bb081 …

fix: M-08 Transfers of The Target Chain's Gas Token Will Fail

---

contracts/SpokePool.sol

> The fill [function](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/SpokePool.sol#L988) of the SpokePool contract is meant to adhere to the IDestinationSettler interface, as dictated by the latest update to the ERC-7683 [specifications](https://github.com/across-protocol/ERCs/blob/d975d7b4b58fa3d1aa6db1763935cfa2ab1444b1/ERCS/erc-7683.md). The fill function is meant to internally call the fillV3Relay [function](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/SpokePool.sol#L864) in order to process the order data, and it does so by [making a delegatecall to its own fillV3Relay function](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contract …

H-01 SpokePool's fill Function Performs Malformed Call

---

contracts/chain-adapters/ForwarderBase.sol

> The ForwarderBase contract has the setCrossDomainAdmin [function](https://github.com/across-protocol/contracts/blob/5a0c67c984d19a3bb843a4cec9bb081734583dd1/contracts/chain-adapters/ForwarderBase.sol#L69) which changes the crossDomainAdmin state [variable](https://github.com/across-protocol/contracts/blob/5a0c67c984d19a3bb843a4cec9bb081734583dd1/contracts/chain-adapters/ForwarderBase.sol#L20). This variable is used to give access control to almost all functions within the contract, including those that are meant to be used to complete L1->L3 message passing and asset transfers. When calling setCrossDomainAdmin, it is assumed that there are no outstanding operations that need to be passed to another chain. This is because when operations arrive at L2, the original sender of those is the …

improve: L-01: Comment on `setCrossDomainAdmin` Edge Case

---

contracts/erc7683/ERC7683OrderDepositor.sol

> Orders inside the ERC7683OrderDepositor contract may be resolved either by the [_resolve function](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/erc7683/ERC7683OrderDepositor.sol#L244) or by the [_resolveFor function](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/erc7683/ERC7683OrderDepositor.sol#L161). Both functions receive an order and convert it to the [ResolvedCrossChainOrder struct](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/erc7683/ERC7683.sol#L46-L65), which contains the minReceived member of the Output[] type. However, inside both _resolve and _resolveFor functions, the minReceived member is …

fix: L-02 Incorrect Casts

---

deploy/002_deploy_optimism_adapter.ts
deploy/012_deploy_boba_adapter.ts
deploy/024_deploy_base_adapter.ts
deploy/037_deploy_blast_adapter.ts
deploy/038_deploy_mode_adapter.ts
deploy/042_deploy_lisk_adapter.ts
deploy/046_deploy_redstone_adapter.ts
deploy/048_deploy_zora_adapter.ts
deploy/050_deploy_worldchain_adapter.ts
deploy/054_deploy_op_adapter.ts
deploy/consts.ts

This change permits an incremental step towards a totally generic chain adapter deployment for OP stack chains. It does this be restructuring the address mappings for OP stack chains, such that the L1 contract addresses can be resolved solely with the combination of HubPool and SpokPool chain IDs. It also updates the new OP_Adapter deployment script to support a runtime-defined SpokePool chain ID. This is clunkily supplied via the environment because hardhat deploy doesn't seem to permit arbitrary runtime arguments being supplied, but that aside, this should ease subsequent deployments.

improve(OP): More generic OP chain adapter deployment

---

contracts/erc7683/ERC7683Across.sol
contracts/erc7683/ERC7683OrderDepositor.sol

> The [newest changes](https://github.com/across-protocol/ERCs/blob/d975d7b4b58fa3d1aa6db1763935cfa2ab1444b1/ERCS/erc-7683.md) to the ERC-7683 standard redefined the types of some variables. Particularly, the variables storing the chain ID now have the uint64 type instead of uint32, and some addresses are now stored in the bytes32 type. However, the variables declared inside the [AcrossOrderData struct](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/erc7683/ERC7683Across.sol#L8-L18) still have the old types. In particular, the [destinationChainId member](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/erc7683/ERC7683Across.sol#L13) is of type uint32 and the [recipient …

fix: M-03 Types Incompatible With ERC-7683

---

contracts/erc7683/ERC7683Across.sol

> The [PERMIT2_ORDER_TYPE variable](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/erc7683/ERC7683Across.sol#L67) stores the witness data type string, which is supposed to be passed as the witnessTypeString parameter to the permitWitnessTransferFrom function of the Permit2 contract. As such, this variable is supposed to define the typed data that the witness parameter passed to that function was hashed from. However, it instead [specifies](https://github.com/across-protocol/contracts/blob/108be77c29a3861c64bdf66209ac6735a6a87090/contracts/erc7683/ERC7683Across.sol#L70) that the witness parameter has been hashed from the CrossChainOrder type, whereas in reality, [it was hashed from the GaslessCrossChainOrder …

fix: M-06 Incorrect Parameters Passed to permitWitnessTransferFrom

---

contracts/chain-adapters/Solana_Adapter.sol
contracts/libraries/AddressConverters.sol
test/evm/hardhat/chain-adapters/Solana_Adapter.ts

- Small fixes to be added to https://github.com/across-protocol/contracts/pull/672

feat(svm): svm-dev fixes from review

---

programs/svm-spoke/src/instructions/deposit.rs
programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/utils/mod.rs
programs/svm-spoke/src/utils/transfer_utils.rs
scripts/svm/simpleDeposit.ts
scripts/svm/simpleFakeRelayerRepayment.ts
scripts/svm/simpleFill.ts
test/svm/SvmSpoke.Deposit.ts
test/svm/SvmSpoke.Fill.ts
test/svm/SvmSpoke.HandleReceiveMessage.ts
test/svm/SvmSpoke.Routes.ts
test/svm/SvmSpoke.SlowFill.ts
test/svm/SvmSpoke.common.ts

Clients might have enabled [CPI-guards](https://spl.solana.com/token-2022/extensions#cpi-guard) that would prohibit transfers within CPI (e.g. deposits, fills). To support this, we need to transfer all user tokens with spoke pool authority, assuming the client has delegated exact deposit/fill amount.
Fixes: https://linear.app/uma/issue/ACX-3351/use-delegated-transfers-in-svm-spoke

fix: delegated transfers in deposits

---

contracts/SwapAndBridge.sol
contracts/external/interfaces/IERC20Auth.sol

We need to have a way to deposit into the spoke pool **and** perform a `swapAndBridge` using [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612) and [EIP-3009](https://eips.ethereum.org/EIPS/eip-3009). 
This functionality is added with four new functions in the `UniversalSwapAndBridge` contract: `swapAndBridgeWithPermit`, `depositWithPermit`, `swapAndBridgeWithAuthorization`, and `depositWithAuthorization`, where `*WithPermit` indicates usage of an EIP-2612 compliant token, and `*WithAuthorization` indicates usage of an EIP-3009 compliant token.
EIP-2616 is used solely to give an approval to an address without calling `approve` first. This allows us to still use `transferFrom` when using any EIP-2612 token. 
On the other hand, EIP-3009 will simply transfer tokens to the designated …

feat: handle EIP-2612 and EIP-3009 in `SwapAndBridge.sol`

---

contracts/Linea_SpokePool.sol
contracts/Ovm_SpokePool.sol
contracts/PolygonZkEVM_SpokePool.sol
contracts/Polygon_SpokePool.sol
contracts/SpokePool.sol
contracts/ZkSync_SpokePool.sol
contracts/interfaces/SpokePoolInterface.sol
contracts/test/MockSpokePool.sol
test/evm/foundry/fork/BlacklistedRelayerRecipient.t.sol
test/evm/hardhat/MerkleLib.Proofs.ts
test/evm/hardhat/MerkleLib.utils.ts
test/evm/hardhat/SpokePool.Admin.ts
test/evm/hardhat/SpokePool.ClaimRelayerRefund.ts
test/evm/hardhat/SpokePool.ExecuteRootBundle.ts
test/evm/hardhat/chain-specific-spokepools/Arbitrum_SpokePool.ts
test/evm/hardhat/chain-specific-spokepools/Ethereum_SpokePool.ts
test/evm/hardhat/chain-specific-spokepools/Optimism_SpokePool.ts
test/evm/hardhat/chain-specific-spokepools/Polygon_SpokePool.ts
test/svm/utils.ts

Proposed changes in this PR:
- Revert to using address for internal functions and data structures in the SpokePool and related contracts.

feat: revert bytes32 conversion for internal functions

---

programs/svm-spoke/src/instructions/bundle.rs
programs/svm-spoke/src/instructions/slow_fill.rs
test/svm/SvmSpoke.SlowFill.ts
test/svm/utils.ts

We had custom serialization implementation when hashing relayer refund and slow fill leaves. This just concatenated array elements without encoding array length. This PR fixes by using Anchor's borch serializer that encodes this more consistently.

fix(svm): use borch serializer

---

contracts/SpokePool.sol
scripts/buildSampleTree.ts
test/evm/hardhat/MerkleLib.Proofs.ts
test/evm/hardhat/SpokePool.Deposit.ts
test/evm/hardhat/SpokePool.Relay.ts
test/evm/hardhat/chain-specific-spokepools/Polygon_SpokePool.ts
test/evm/hardhat/constants.ts
test/evm/hardhat/fixtures/SpokePool.Fixture.ts

This PR re-works the `_getV3RelayHash` method.
Gas comparison:
Comparison of fills with no Message field ("0x")
Old: 111308
New: 111236
saving: 72
Comparison of fill with 1kb message field ("0x"+"69".repeat(512))
Old:  123987
New: 122837
Saving: 1150
Comparison of fill with 10kb message field ("0x"+"69".repeat(10240))
Old: 316828
New: 293517
Saving: 23311

feat: improve _getV3RelayHash method

---

programs/svm-spoke/src/instructions/fill.rs
programs/svm-spoke/src/instructions/slow_fill.rs
programs/svm-spoke/src/lib.rs
programs/svm-spoke/src/state/fill.rs
programs/svm-spoke/src/utils/merkle_proof_utils.rs
scripts/svm/closeRelayerPdas.ts
src/SvmUtils.ts
test/svm/SvmSpoke.Bundle.ts
test/svm/SvmSpoke.Fill.ts
test/svm/SvmSpoke.RefundClaims.ts
test/svm/SvmSpoke.SlowFill.AcrossPlus.ts
test/svm/SvmSpoke.SlowFill.ts
test/svm/SvmSpoke.TokenBridge.ts
test/svm/utils.ts

After having implemented Across+ that replaces message with its hash in the emitted fill events, it becomes overly complex to discover `fill_status` PDA addresses as its derivation requires knowledge of full message. This PR overcomes this issue by changing how relay hash is calculated, so that message is replaced with its hash before calculating the hash of the whole relay data struct. This also drops relay hash and relay data parameters in the `close_fill_pda` by storing fill deadline in the `fill_status` account.
Same EVM changes are done in #779

fix: hash message hash in relay hash

---

scripts/checkStorageLayout.sh
storage-layouts/AlephZero_SpokePool.json
storage-layouts/PolygonZkEVM_SpokePool.json
storage-layouts/Redstone_SpokePool.json
storage-layouts/Scroll_SpokePool.json
storage-layouts/WorldChain_SpokePool.json
storage-layouts/Zora_SpokePool.json

The `forge inspect` behavior changed in one of the `nightly` builds recently, and this broke CI because our CI pulls from the latest `nightly` version each time it runs. [The default behavior prints a table now](https://github.com/foundry-rs/foundry/blob/00efa0d5965269149f374ba142fb1c3c7edd6c94/crates/forge/bin/cmd/inspect.rs#L184), which honestly is pretty nice to look at and maybe we should use it. However, the table is a bit harder to modify using simple `jq` bash commands like we do today.
However, the simplest fix for now is to add the `--json` flag to `inspect` command. 
I've also added other spoke pools to the script.

fix: Add `--json` flag to checkStorageLayout's `forge inspect` command

---

README.md

I got a new computer and had some issues setting up the repo. these instructions show what I had to do to get it working while debugging the installation

Update README.md with debug instructions

---

src/svm/relayHashUtils.ts

- Use borsh serialiser in `relayHashUtils.ts` to be consistent with svm programs

feat(svm): borsh serialise in scripts

---

Anchor.toml
scripts/svm/queryEvents.ts
src/svm/solanaProgramUtils.ts

- Add script to read and print svm events in a human readable format.

feat(svm): query events script

---

scripts/svm/bridgeLiabilityToHubPool.ts
scripts/svm/executeRebalanceToHubPool.ts
scripts/svm/executeRebalanceToSpokePool.ts
scripts/svm/proposeRebalanceToHubPool.ts
scripts/svm/proposeRebalanceToSpokePool.ts
scripts/svm/remoteHubPoolPauseDeposits.ts
scripts/svm/remoteHubPoolSetDepositRoute.ts
scripts/svm/remotePauseDeposits.ts
scripts/svm/utils/helpers.ts
src/svm/cctpHelpers.ts
src/svm/constants.ts
src/svm/conversionUtils.ts
src/svm/helpers.ts
src/svm/index.ts
src/svm/solanaProgramUtils.ts
test/svm/SvmSpoke.HandleReceiveMessage.ts
test/svm/SvmSpoke.TokenBridge.ts

- Finish the organization of utility functions with `constants`, `helpers`, and `cctpHelpers` shared utilities.
- Enhance `cctpHelpers` with data integrity checks.

feat(svm): reorganize remaining svm tools

---

src/svm/instructionParamsUtils.ts
src/svm/transactionUtils.ts

addresses an issue we were seeing with unit tests after an anchor update. Now, all tests work.
reason this was needed is as follows:
```
Note that after you create or extend a lookup table, it must "warm up" for one slot before the lookup table or newly added addresses can be used in transactions. You can only access lookup tables and addresses added in slots prior to the current one.
```

fix: address LUT issues on tests

---

src/svm/helpers.ts

- Shorten SVM chain ids to 6 bytes to prevent them from overflowing js Number type
getSolanaChainId("devnet") => `133268194659241`
getSolanaChainId("mainnet")=> `34268394551451`

feat(svm): shorten svm chain ids

---

contracts/SpokePool.sol
contracts/interfaces/V3SpokePoolInterface.sol
contracts/test/MockSpokePool.sol
test/evm/hardhat/SpokePool.Relay.ts
test/evm/hardhat/SpokePool.SlowRelay.ts

This PR adds a small addition to https://github.com/across-protocol/contracts/pull/805

feat: extend current add-legacy-fill-method-svm-dev

---

programs/svm-spoke/src/instructions/bundle.rs
test/svm/SvmSpoke.Bundle.ts

```
The instruction_params account used in the ExecuteRelayerRefundLeaf instruction remains open after execution,
despite becoming unnecessary once the instruction completes. Leaving the account open leads to resource
inefficiencies. Although a close_instruction_params function can address this issue, it introduces
unnecessary complexity. A more elegant and efficient approach is to leverage Anchor's close attribute to
handle account closure automatically. Unclosed accounts within Solana persist on-chain indefinitely, wasting
storage resources and keeping the lamports from rent locked and unavailable for other operations.
Consider using Anchor's close attribute to ensure that the instruction_params account is automatically
closed, reclaiming resources and …
```

fix(svm): L-09 close instruction_params account after execute_relayer_refund_leaf

---

programs/svm-spoke/src/error.rs

```
Throughout the codebase, multiple instances of unused errors were identified:
- InvalidRoutePDA
- NotFilled
- InvalidUint128
Consider removing any unused errors.
```
This PR addresses the issue by removing unused errors.

fix(svm): N-02 remove unused errors

---

programs/multicall-handler/src/lib.rs

```
Across deposits may include additional message data that must be processed during relayer fills, in which
case the data is deserialized and processed as various accounts and instructions that are invoked on the
message handler specified in the relayer data. In the provided multicall_handler example, the handler_signer
may be included as an additional signer in the CPI calls decoded from the message. However, it may be
included when not necessary. This is because, in each program call, use_handler_signer is set if any accounts
in the call match the handler_signer key, but it is never reset to false before checking subsequent calls.
Consider correcting this logic by resetting the value of use_handler_signer at the top of the outermost for
loop to avoid …
```

fix(svm): N-04 reset use of PDA signer in multicall handler

---

programs/svm-spoke/src/instructions/instruction_params.rs

```
The Accounts derive macro includes an attribute named Instruction that provides access to the instruction’s
arguments within the struct utilizing the macro. However, in the WriteInstructionParamsFragment struct, this
attribute is unnecessary, as neither the offset nor the fragment arguments are used within the struct.
This inclusion may lead to confusion for developers working on the codebase. As such, consider removing the
unused attribute to improve code clarity and maintainability.
```
This PR addresses the issue by removing the unused instruction attribute.

fix(svm): N-06 remove unused instruction attribute

---

programs/svm-spoke/src/constraints.rs
programs/svm-spoke/src/error.rs
programs/svm-spoke/src/instructions/refund_claims.rs
programs/svm-spoke/src/lib.rs
test/svm/SvmSpoke.RefundClaims.ts

> The [claim_relayer_refund](https://github.com/across-protocol/contracts/blob/401e24ccca1b3af919dd521e58acd445297b65b6/programs/svm-spoke/src/instructions/refund_claims.rs#L76) and [claim_relayer_refund_for](https://github.com/across-protocol/contracts/blob/401e24ccca1b3af919dd521e58acd445297b65b6/programs/svm-spoke/src/instructions/refund_claims.rs#L152) functions share almost identical logic, with the primary distinction being the refund address. This duplication introduces maintainability challenges, as future updates may need to be applied to both functions simultaneously, increasing the risk of inconsistencies.
> 
> To streamline the code and reduce redundancy, consider implementing the following refactor:
>
> Abstract the common logic from both …

fix(svm): N-03 remove duplicate logic

---

programs/svm-spoke/src/lib.rs

**Changes proposed in this PR:**
- Fixes the following issue identified by Open Zeppelin:
> The [deposit_v3](https://github.com/across-protocol/contracts/blob/0f2600f83e8a5738d0d62a78b05ff37adda4c1c9/programs/svm-spoke/src/lib.rs#L250) and [deposit_v3_now](https://github.com/across-protocol/contracts/blob/0f2600f83e8a5738d0d62a78b05ff37adda4c1c9/programs/svm-spoke/src/lib.rs#L283) functions use the same parameter name, fill_deadline, with differing semantics. In deposit_v3, it is an absolute timestamp, whereas in deposit_v3_now, it is an offset added to the current time.
> 
> The documentation lacks clarity about this distinction, increasing the likelihood of errors. Users might mistakenly pass an absolute timestamp to deposit_v3_now, leading to a computed deadline (current_time + …

feat(svm): N-05 Ambiguous Parameter Usage for fill_deadline

---

programs/svm-spoke/src/common/v3_relay_data.rs
programs/svm-spoke/src/instructions/bundle.rs
programs/svm-spoke/src/instructions/slow_fill.rs
programs/svm-spoke/src/state/instruction_params.rs

- Fix audit issue:
```
Throughout the codebase, the following structs use the InitSpace macro unnecessarily:
FillV3RelayParams
ExecuteRelayerRefundLeafParams
RequestV3SlowFillParams
ExecuteV3SlowRelayLeafParams
These accounts are initialized using the initialize_instruction_params method, which creates empty accounts with a size specified in the function's instructions. Consequently, the InitSpace macro, which implements the Space trait, becomes redundant as the INIT_SPACE constant generated by this trait is not utilized. The inclusion of the InitSpace macro in these cases adds unnecessary overhead and obscures the intended logic, given that its functionality is not employed.
Consider removing the InitSpace macro from these structs to simplify the codebase and …
```

feat(svm): L-06 Unnecessary Use of InitSpace Macro

---

programs/svm-spoke/src/event.rs
programs/svm-spoke/src/instructions/admin.rs
test/svm/SvmSpoke.Ownership.ts

Fix the following issue identified by OZ:
```
The [transfer_ownership](https://github.com/across-protocol/contracts/blob/0f2600f83e8a5738d0d62a78b05ff37adda4c1c9/programs/svm-spoke/src/instructions/admin.rs#L110) function does not emit any relevant events after performing sensitive actions.
Consider emitting events after sensitive changes take place to facilitate off-chain tracking and monitoring.
```

feat(svm): L-07 transfer ownership event

---

programs/svm-spoke/src/event.rs
programs/svm-spoke/src/utils/message_utils.rs

- Fixes the following issue identifier by Open Zeppelin:
> During development, having well-described TODO comments will make the process of tracking and resolving them easier. Without this information, these comments might age and important information for the security of the system might be forgotten by the time it is released to production.
> 
> Throughout the [codebase](hhttps://github.com/across-protocol/contracts/tree/0f2600f83e8a5738d0d62a78b05ff37adda4c1c9), multiple instances of unaddressed TODO comments were identified:
> 
> In [line 87](https://github.com/across-protocol/contracts/blob/0f2600f83e8a5738d0d62a78b05ff37adda4c1c9/programs/svm-spoke/src/event.rs#L87) of event.rs.
> 
> In [line 91](https://github.com/across-protocol/contracts/blob/0f2600f83 …

feat(svm): N-07 TODO Comments in the Code

---

programs/svm-spoke/src/lib.rs

**Changes proposed in this PR:**
- Fixes the following issue identified by Open Zeppelin:
> Throughout the codebase, multiple instances of incomplete or misleading comments were identified:
> This [comment](https://github.com/across-protocol/contracts/blob/0f2600f83e8a5738d0d62a78b05ff37adda4c1c9/programs/svm-spoke/src/lib.rs#L313) above unsafe_deposit_v3 states that the deposit_nonce is not used to derive the deposit_id, whereas [it is](https://github.com/across-protocol/contracts/.blob/0f2600f83e8a5738d0d62a78b05ff37adda4c1c9/programs/svm-spoke/src/instructions/deposit.rs#L229) so used.
> 
> This [comment](https://github.com/across-protocol/contracts/blob/401e24ccca1b3af919dd521e58acd445297b65b6/programs/svm-spoke/src/lib.rs#L489) above execute_relayer_refund_leaf states that it can …

feat(svm): N-01 Incomplete or Misleading Comments

---

contracts/interfaces/V3SpokePoolInterface.sol

These are still needed for parsing of historical FilledV3Relay events.

fix(SpokePool): Reconstitute FilledV3Relay events

---

programs/multicall-handler/src/lib.rs

> The [handle_v3_across_message](https://github.com/across-protocol/contracts/blob/401e24ccca1b3af919dd521e58acd445297b65b6/programs/multicall-handler/src/lib.rs#L17) function within multicall_handler relies on find_program_address to derive the public key of a PDA and its canonical bump value, using a seed and the program ID. The find_program_address function computes a valid PDA by calling create_program_address iteratively, starting with a bump of 255 and decrementing the bump until a valid address is found. While this ensures that a valid PDA is derived, the iterative process is computationally expensive, which is problematic, particularly in functions like handle_v3_across_message that may execute multiple instructions. If not optimized, this approach …

fix(svm): L-05 comment on efficient handler_signer PDA derivation

---

programs/svm-spoke/src/instructions/deposit.rs
src/svm/conversionUtils.ts
test/svm/SvmSpoke.Deposit.ts

- Updated deposit ID storage format to use big-endian encoding 
- Refactored byte manipulation logic to ensure consistent big-endian encoding and decoding for 32byte arrays
Motivation:
Previously, "safe" (`deposit_v3`) deposit IDs were stored in little-endian (LE) format, causing friction for relayers and off-chain tools due to format conversions. Challenges included:
1. Relayers had to convert BE (EVM standard) to LE, adding complexity.
2. Special handling was required to extract and parse IDs stored in LE format see [this](https://github.com/across-protocol/contracts/blob/25fc095c2d75da8922a220acfcea8c4dd5c9295f/src/svm/solanaProgramUtils.ts#L213-L228)
3. Diverged from EVM conventions, complicating cross-chain operations.
Solution:
This PR stores "safe" …

feat(svm): Refactor deposit ID to use big-endian encoding in Bytes32 format

---

contracts/SpokePool.sol
contracts/interfaces/V3SpokePoolInterface.sol
test/evm/hardhat/SpokePool.Deposit.ts
test/evm/hardhat/SpokePool.Relay.ts
test/evm/hardhat/SpokePool.SlowRelay.ts
test/evm/hardhat/constants.ts

The purpose of this revert it to ensure `master` is identical to the current Across onchain deployments. This commit was ultimately not included in the most recent `SpokePool` deployment as it was not sufficiently audited when originally merged.
This reverts commit fac5dd1dac63ac1a80f0f6a97b6b6e246693f4f6.

Revert "improve(SpokePool): _depositV3 interprets `exclusivityParameter` as an offset, or a timestamp (#670)"

---

.github/workflows/publish.yml
package.json

CI publish fails with
```
error @solana/web3-v2.js@2.0.0: The engine "node" is incompatible with this module. Expected version ">=20.18.0". Got "18.20.6"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

ci: fix publish build

---

contracts/SpokePool.sol
test/evm/hardhat/fixtures/SpokePool.Fixture.ts

If we have two separate methods to calculate the relay hash, separated by whether the L2's spoke pool is updated or not, then relayers may produce two valid deposits for the same fill, or even worse, a slow fill may be executed for a deposit which has already been filled. To mitigate this, we should consider not changing the way we calculate relay hashes for evm chains.

fix: use entire message when calculating relay hash for evm chains

---

contracts/SpokePool.sol
test/evm/hardhat/SpokePool.Deposit.ts

This removes a sharp edge for pre-fill deposits, where the deposit comes after the fill. Permitting a historical fillDeadline gives more flexibility to the relayer around when they submit the deposit on the origin chain.

feat(SpokePool): Permit historical fillDeadline on deposit

---

contracts/SpokePool.sol
contracts/libraries/AddressConverters.sol
test/evm/hardhat/SpokePool.Deposit.ts

This fixes a bug where a caller can set the depositor to an invalid EVM address, making refunds impossible.

fix: add check to ensure depositor is a valid EVM address

---

programs/svm-spoke/src/instructions/deposit.rs
programs/svm-spoke/src/lib.rs
test/svm/SvmSpoke.Deposit.ts

- Mimics the changes in https://github.com/across-protocol/contracts/pull/870 in EVM:
```
This removes a sharp edge for pre-fill deposits, where the deposit comes after the fill. Permitting a historical fillDeadline gives more flexibility to the relayer around when they submit the deposit on the origin chain.
```

feat(svm): Permit historical fillDeadline on deposit

---

deployments/deployments.json
package.json
scripts/svm/simpleFill.ts

feat(svm): fix simple fill script

---

scripts/svm/simpleDeposit.ts

This PR extends the current SimpleDeposit script to show how to use the [solana memo program](https://spl.solana.com/memo) to append a deposit ID.
See example tx that does not have the memo [here](https://explorer.solana.com/tx/kiKk6exRDQg7bqmBnVFXmfTwdoV16grKTm2citdRNYR836s6gxV366tpLXSdxtzHhqDGMHFmEwNpsL5uqkTBRMD?cluster=devnet) and one that has it [here](https://explorer.solana.com/tx/PnPBXiEj62dX7Kuvn3vZ33zhXq7MoXJ5JM5qYoxzyYfkZtEJCCerQbKE9bJCPc6oT6ng1TtdyKcFd8hSMsskd2i?cluster=devnet).

feat: show how to add integrator ID to a deposit

---

README.md

Generally clean up docs and add section on how upgradeability works

improve(README): Add details about upgradeability

---

contracts/ZkSync_SpokePool.sol
storage-layouts/ZkSync_SpokePool.json

This contract gets extended by the Lens_SpokePool which doesn't add any storage but we should add it in case a future variable gets added to the Lens_SpokePool

fix(ZkSync_SpokePool): Add __gap

---

contracts/libraries/CircleCCTPAdapter.sol

- The casting to bytes20 will fetch the first 20 bytes of the return value. However, the functions in Solidity return abi.encoded data, which means in particular, that if an address is returned from the feeRecipient function, the returned feeRecipient.length will be equal to 32 and the address will be included in the last 20 bytes of that data (will be padded with 12 zeroes at the beginning). As a result, casting feeRecipient to bytes20 will capture only the first 8 bytes of the returned address. You can get the full address by casting the data to uint160 instead (you may need to cast it to bytes32 and uint256 first).
- The feeRecipient.length is not validated. It means that for example, in case of a call to nonexistent contract or a call to a contract with a fallback function which …

fix(CCTPAdapter): Fix feeRecipient check to determine V2 vs V1

---

scripts/svm/findFillStatusFromFillStatusPda.ts

Rename from `@solana/web3-v2.js` to `@solana/kit` was missing in one of merged PRs that still referenced the v2

fix: renamed solana kit import

---

.eslintrc.js
tasks/evmRelayMessageWithdrawal.ts

When trying to run the version in `master`, I get `Error HH310: Invalid param --spokePool. Command line params must be lowercase.`
This is why I changed params to lowercase.
FYI @bmzig

fix(tasks): fix usage comment + typo in `evm-relay-message-withdrawal`

---

contracts/interfaces/IHypXERC20Router.sol
contracts/interfaces/IOFT.sol

Bring in some external interfaces from upcoming OFT + xERC20 update. Exact copies from [audit branch](https://github.com/across-protocol/contracts/tree/march-25-evm-audit). These are nice to have in the `relayer` repo for typechain.

chore: add OFT and xERC20 interface files for typechain generation

---

contracts/chain-adapters/ZkStack_CustomGasToken_Adapter.sol

> The ZkStack_CustomGasToken_Adapter contract is used to send messages from L1 to ZK Stack-based chains with a custom gas token. The public functions within this contract are expected to be called via delegatecall, which will execute this contract's logic within the context of the originating contract. Particularly, the HubPool will [delegatecall](https://github.com/across-protocol/contracts/blob/77761d74152e319e6edd6d4d766cb46c39e6f38d/contracts/HubPool.sol#L901-L909) the [relayTokens function](https://github.com/across-protocol/contracts/blob/77761d74152e319e6edd6d4d766cb46c39e6f38d/contracts/chain-adapters/ZkStack_CustomGasToken_Adapter.sol#L178). This relayTokens function is used to bridge tokens to a ZK Stack chain. This function calls _pullCustomGas to define txBaseCost on [line …

L-01 Custom Gas Tokens Can Get Stuck In `HubPool`

---

contracts/chain-adapters/ZkStack_Adapter.sol
contracts/chain-adapters/ZkStack_CustomGasToken_Adapter.sol
test/evm/foundry/local/ZkStack_Adapter.t.sol

> The relayTokens functions [[1]](https://github.com/across-protocol/contracts/blob/77761d74152e319e6edd6d4d766cb46c39e6f38d/contracts/chain-adapters/ZkStack_Adapter.sol#L154) [[2]](https://github.com/across-protocol/contracts/blob/77761d74152e319e6edd6d4d766cb46c39e6f38d/contracts/chain-adapters/ZkStack_CustomGasToken_Adapter.sol#L178) are used to bridge tokens from L1 to ZK Stack. Both instances define a txHash variable [[1]](https://github.com/across-protocol/contracts/blob/77761d74152e319e6edd6d4d766cb46c39e6f38d/contracts/chain-adapters/ZkStack_Adapter.sol#L164) [[2]](https://github.com/across-protocol/contracts/blob/77761d74152e319e6edd6d4d766cb46c39e6f38d/contracts/chain-adapters/ZkStack_CustomGasToken_Adapter.sol#L189) which will later be assigned to the transaction hash value …

N-02 Relay Tokens From L1 Emits Empty Transaction Hash When Relaying USDC through CCTP

---

contracts/chain-adapters/ZkStack_Adapter.sol
contracts/chain-adapters/ZkStack_CustomGasToken_Adapter.sol

This variable is no longer used. Removing it addresses a warning being emitted by solc.
```
Warning: Unused local variable.
--> contracts/chain-adapters/ZkStack_CustomGasToken_Adapter.sol:152:9:
|
152 |         bytes32 canonicalTxHash = BRIDGE_HUB.requestL2TransactionDirect(
|         ^^^^^^^^^^^^^^^^^^^^^^^
```

chore(ZkStack_Adapter): Remove unused canonicalTxHash

---

contracts/Polygon_SpokePool.sol
test/evm/hardhat/chain-specific-spokepools/Polygon_SpokePool.ts

1. Prevent EIP7702-aided calls to `executeRelayerRefundLeaf` from a smart contract 
2. Prevent a nested multicall that can bypass the existing `_validateMulticall` checks

fix(PolygonSpokePool): enhance PolygonSpokePool reentrancy guard

---

contracts/SpokePoolV3Periphery.sol
contracts/interfaces/SpokePoolV3PeripheryInterface.sol
contracts/libraries/PeripherySigningLib.sol
test/evm/foundry/local/SpokePoolPeriphery.t.sol

This PR adds an option so that callers can have their bridge output increased proportionally to the improvement the swap returns over the min allowed swap output.
This essentially assumes the bridge quote was generated based on the min and that the percentage should stay fixed.

feat: optionally adjust output amount by swap price improvement over min

---

contracts/handlers/MulticallHandler.sol
package.json
test/evm/foundry/local/MulticallHandler.t.sol
yarn.lock

This is a bit clunky, but it adds a way to do balance injection for calls to multicall handler, so the calldata can use the updated balance.
It's done as a nested call to keep the MulticallHandler backwards compatible.

feat: add balance injection to multicall handler calls

---

package.json
tasks/enableL1TokenAcrossEcosystem.ts
yarn.lock

BSC routes are still required as a destination chain on v3 SpokePools, so don't skip it. BSC is separately skipped as an origin chain though.

improve(enableToken): Don't skip BSC

---

contracts/chain-adapters/Universal_Adapter.sol

In the Universal_Adapter contract, the [inline documentation states](https://github.com/across-protocol/contracts/blob/c5d7541037d19053ce2106583b1b711037483038/contracts/chain-adapters/Universal_Adapter.sol#L74) that the relayTokens function "only uses the CircleCCTPAdapter to relay USDC tokens to CCTP enabled L2 chains". While this is partially true for that token, the new implementation also allows to use the [OFT method](https://github.com/across-protocol/contracts/blob/c5d7541037d19053ce2106583b1b711037483038/contracts/chain-adapters/Universal_Adapter.sol#L90-L92).
Consider updating the documentation to reflect the current behavior of the functionality.

[L-02] Misleading Documentation

---

contracts/AdapterStore.sol

Note: added a part of suggested change: IOFT validation on AdapterStore.sol side
---
In the SpokePool contract, there is no standard way of checking whether a contract supports specific interfaces or features. In particular, when adding a messenger, the [single check](https://github.com/across-protocol/contracts/blob/c5d7541037d19053ce2106583b1b711037483038/contracts/SpokePool.sol#L1740) being performed is whether the input address matches its token function against the one passed. As the token function is pretty common in a diverse set of contracts, a contract could be mistakenly passed that implements a token function and retrieves the particular token, but is not an IOFT type of contract. In such a scenario, the assignment will pass but will result in unexpected situations.
In the …

[L-01] Lack of Validation On Linked Messengers

---

contracts/libraries/OFTTransportAdapter.sol
contracts/test/MockOFTMessenger.sol
test/evm/foundry/local/Universal_Adapter.t.sol
test/evm/foundry/local/Universal_SpokePool.t.sol

The OFTTransportAdapter contract implements the [_transferViaOFT function](https://github.com/across-protocol/contracts/blob/c5d7541037d19053ce2106583b1b711037483038/contracts/libraries/OFTTransportAdapter.sol#L57), meant to interact with the OFT messenger and send the funds with that method. To do so, it first [quotes the fees](https://github.com/across-protocol/contracts/blob/c5d7541037d19053ce2106583b1b711037483038/contracts/libraries/OFTTransportAdapter.sol#L85), which are returned as [native or ZRO token fees](https://github.com/across-protocol/contracts/blob/c5d7541037d19053ce2106583b1b711037483038/contracts/interfaces/IOFT.sol#L18-L19). Later, this same output is used as [part of the message](https://github.com/across-protocol/contracts/blob/c5d7541037d19053ce2106583b1b711037483038/ …

[M-03] OFT Transfer Might Revert Due To Non-Zero ZRO Token Fee Quote

---

contracts/AdapterStore.sol
contracts/libraries/OFTTransportAdapterWithStore.sol

Providing a specific security contact (such as an email or ENS name) within a smart contract significantly simplifies the process for individuals to communicate if they identify a vulnerability in the code. This practice is quite beneficial as it permits the code owners to dictate the communication channel for vulnerability disclosure, eliminating the risk of miscommunication or failure to report due to a lack of knowledge on how to do so. In addition, if the contract incorporates third-party libraries and a bug surfaces in those, it becomes easier for their maintainers to contact the appropriate person about the problem and provide mitigation instructions.
Throughout the codebase, multiple instances of contracts missing a security contact were identified:
The [MessengerTypes …

[N-09] Lack of Security Contact

---

contracts/SpokePool.sol
test/evm/foundry/local/Universal_SpokePool.t.sol
test/evm/hardhat/chain-adapters/Arbitrum_Adapter.ts
test/evm/hardhat/chain-specific-spokepools/Arbitrum_SpokePool.ts

In the SpokePool contract, the [_setOftMessenger](https://github.com/across-protocol/contracts/blob/c5d7541037d19053ce2106583b1b711037483038/contracts/SpokePool.sol#L1739) function allows for adding or updating an OFT messenger address for a particular token. However, if the current messenger is compromised or needs to be taken down, there is no functionality that would allow the admin to remove it from the available messengers (without replacing it with a new one).
Furthermore, it is not possible to use the _setOftMessenger function to set it to zero, as there is a [validation done over its token](https://github.com/across-protocol/contracts/blob/c5d7541037d19053ce2106583b1b711037483038/contracts/SpokePool.sol#L1740) that would revert if the messenger is set to the zero address or to an …

[M-02] Compromised Messengers Cannot Be Removed

---

contracts/SpokePool.sol

Addressed partially. Reason:
`function _bridgeTokensToHubPool(uint256 amountToReturn, address l2TokenAddress) internal virtual` in `SpokePool` cannot be private, as it's virtual. It needs to be at least internal

[N-05] Function Visibility Overly Permissive

---

contracts/SpokePoolPeriphery.sol

The [performSwap function](https://github.com/across-protocol/contracts/blob/b84dbfae35030e0f2caa5509b632c10106a32330/contracts/SpokePoolPeriphery.sol#L67) of the SwapProxy contract allows to provide tokens for a swap to a specified exchange using several different methods. In particular, it allows to approve tokens for the swap [through the Permit2 contract](https://github.com/across-protocol/contracts/blob/b84dbfae35030e0f2caa5509b632c10106a32330/contracts/SpokePoolPeriphery.sol#L86-L101). In order to do that, it [approves the given token amount to the Permit2 contract](https://github.com/across-protocol/contracts/blob/b84dbfae35030e0f2caa5509b632c10106a32330/contracts/SpokePoolPeriphery.sol#L86), and [calls the permit function of the Permit2 …

[H-01] Incorrect Nonce Passed to the Permit2.permit Function

---

contracts/SpokePoolPeriphery.sol
contracts/interfaces/SpokePoolPeripheryInterface.sol

Throughout the codebase, there are some instances of unused code, which could be removed:
In the SpokePoolPeriphery.sol file, the InvalidSignatureLength error is unused.
In the SpokePoolPeripheryInterface.sol file, the import is unused.
To improve the overall clarity, intentionality, and readability of the codebase, consider removing any currently unused code.

[N-10] Unused Code

---

contracts/SpokePoolPeriphery.sol
contracts/handlers/MulticallHandler.sol
contracts/interfaces/SpokePoolPeripheryInterface.sol

Throughout the codebase, several instances of typographical errors were identified:
On line 48 of the MulticallHandler.sol file, \calldData\ should be \callData\.
On line 113 of the SpokePoolPeripheryInterface.sol file, \on\ could be removed.
On line 500 of the SpokePoolPeriphery.sol file, \depositData/swapAndDepositData\ could be \DepositData/SwapAndDepositData\.
Consider correcting all instances of typographical errors in order to improve the clarity and readability of the codebase.

[N-08] Typographical Errors

---

contracts/SpokePoolPeriphery.sol
contracts/handlers/MulticallHandler.sol

Throughout the codebase, there are several places where the documentation could be expanded to better describe the code. The instances are listed below:
The makeCallWithBalance function of the MulticallHandler contract allows to replace specified offsets of a given call data with current token or native balances, but the purpose of this function and the correct way of using it may not be immediately clear to the users, it would benefit from the additional documentation describing its purpose, limitations and correct usage. One additional limitation that could also be listed is that this function is not capable of filling negative balances, hence decentralized exchanges, which require input token amounts to be nagative, are not supported.
The documentation of the swapAndBridge, …

[N-05] Insufficient Documentation

---

contracts/SpokePoolPeriphery.sol
test/evm/foundry/local/SpokePoolPeriphery.t.sol

Currently, every DepositData and SwapAndDepositData payload must include a hard-coded fee recipient address, and upon successful deposit or swap-and-bridge the periphery pays submission fees to that exact address.
While this ensures the user knows in advance exactly who will receive their fee, it also prevents open relayer competition or fallback options when the chosen relayer is unavailable or underperforms.
Consider keeping the explicit fee recipient field option in SwapAndDepositData but introduce a "zero‐address" convention:
If the fee recipient is equal to the zero address, the periphery should default to using msg.sender as the payee.
Otherwise, transfer fees to the signed recipient as today.

[L-05] Inflexible Fee Recipient Field Blocks Open Relaying

---

contracts/interfaces/SpokePoolPeripheryInterface.sol
contracts/libraries/PeripherySigningLib.sol

The PeripherySigningLib library contains the EIP-712 encodings of certain types as well as helper functions to generate their EIP-712 compliant hashed data.
However, the data type of the SwapAndDepositData struct is incorrect as it contains the TransferType member of an enum type, which is not supported by the EIP-712 standard.
Consider replacing the TransferType enum name used to generate the SwapAndDepositData's data type with uint8 in order to be compliant with EIP-712.

[M-05] Incorrect EIP-712 Encoding

---

contracts/SpokePoolPeriphery.sol
contracts/interfaces/SpokePoolPeripheryInterface.sol

Throughout the codebase, there are several instances of misleading documentation. The examples are listed below.
The swapAndBridgeWithPermit and depositWithPermit functions are documented to fail if the provided token does not support the EIP-2612 permit function. However, the implementation contradicts this statement as in both functions, the call to permit is wrapped in a try/catch block, and any failure is silently ignored.
The comment refers to the transferWithAuthorization function, while it should mention the receiveWithAuthorization function instead.
The documentation of the SpokePoolPeriphery contract and the SpokePoolPeripheryInterface interface contain an outdated comment claiming that certain variables are not marked immutable or set in the constructor to allow deterministic …

[N-12] Misleading Documentation

---

contracts/SpokePoolPeriphery.sol

In the _swapAndBridge function, the adjusted output amount is calculated as the product of depositData.outputAmount and returnAmount divided by minExpectedInputTokenAmount
If depositData.outputAmount * returnAmount exceeds 2^256–1, the transaction will revert immediately on the multiply step, even when the eventual division result would fit. This intermediate overflow is invisible to users, who only see a generic failure, without an explanatory error message.
Consider using OpenZeppelin's Math.mulDiv(a, b, c) to compute floor(a*b/c) without intermediate overflow, or documenting the possible overflow scenario.

[L-03] Integer Overflow in the _swapAndBridge Function

---

contracts/SpokePoolPeriphery.sol
contracts/handlers/MulticallHandler.sol
test/evm/foundry/local/SpokePoolPeriphery.t.sol

Throughout the codebase, there are several places where the code could be optimized in order to save gas. The examples are:
1. The checks validating that a given address refers to a contract in lines 204, 231 and 553 are not necessary as in case when the addresses do not refer to contracts, the subsequent calls at lines 207, 233 and 555 will revert as the Solidity compiler inserts similar code size checks before each high-level call.
2. The "0x" string passed to permit call could be replaced with "".
3. The check could be removed as the same check is already performed in SpokePools. This would additionally allow users to deposit non-native tokens through the SpokePoolPeriphery.deposit function.
4. The replacement argument of the makeCallWithBalance function could be stored in calldata …

[N-03] Optimization Opportunities

---

package.json
src/DeploymentUtils.ts

With exported `deployments`, consumers of this repo have flexibility to add their own utility fns over it

improve: export `deployments`

---

package.json
yarn.lock

Vulnerability in sha.js <= 2.4.11 https://github.com/advisories/GHSA-95m3-7q98-8xr5

chore: Update sha.js version

---

hardhat.config.ts

I didn't want to make the diff too large to review so I'll save testnet/zksync configs for follow up

refactor(hardhat.config): Use default hardhat config where appropriate 

---

scripts/preCommitHook.sh

When constants.json is generated the ending new line is stripped, this should fix it

fix: Format constants file on pre commit hook
